/*
 * Copyright(c) RIB Software GmbH
 */

import { IEntityBase } from '@libs/platform/common';

export interface IMdcDrawingComponentEntityGenerated extends IEntityBase {

  /**
   * Autogenerated
   */
  Autogenerated: boolean;

  /**
   * Description
   */
  Description?: string | null;

  /**
   * EngDrawingFk
   */
  EngDrawingFk: number;

  /**
   * EngDrwCompTypeFk
   */
  EngDrwCompTypeFk: number;

  /**
   * Id
   */
  Id: number;

  /**
   * IsLive
   */
  IsLive: boolean;

  /**
   * MdcCostCodeFk
   */
  MdcCostCodeFk?: number | null;

  /**
   * MdcMaterialCostCodeFk
   */
  MdcMaterialCostCodeFk?: number | null;

  /**
   * MdcMaterialFk
   */
  MdcMaterialFk?: number | null;

  /**
   * MdcProductDescriptionFk
   */
  MdcProductDescriptionFk?: number | null;

  /**
   * Quantity
   */
  Quantity: number;

  /**
   * Quantity2
   */
  Quantity2: number;

  /**
   * Quantity3
   */
  Quantity3: number;

  /**
   * Remark
   */
  Remark?: string | null;

  /**
   * Sorting
   */
  Sorting?: number | null;

  /**
   * Uom2Fk
   */
  Uom2Fk: number;

  /**
   * Uom3Fk
   */
  Uom3Fk: number;

  /**
   * UomFk
   */
  UomFk: number;

  /**
   * Userdefined1
   */
  Userdefined1?: string | null;

  /**
   * Userdefined2
   */
  Userdefined2?: string | null;

  /**
   * Userdefined3
   */
  Userdefined3?: string | null;

  /**
   * Userdefined4
   */
  Userdefined4?: string | null;

  /**
   * Userdefined5
   */
  Userdefined5?: string | null;
}
