/*
 * Copyright(c) RIB Software GmbH
 */

import { IAddressEntity } from './address-entity.interface';
import { IBlobsEntity } from './blobs-entity.interface';
import { ICompanyEntity } from './company-entity.interface';
import { ICompany2BasClerkEntity } from './company-2bas-clerk-entity.interface';
import { ICompany2CostCodeEntity } from './company-2cost-code-entity.interface';
import { ICompany2PrjGroupEntity } from './company-2prj-group-entity.interface';
import { ICompany2TextModuleEntity } from './company-2text-module-entity.interface';
import { ICompanyNumberEntity } from './company-number-entity.interface';
import { ICompanyRoleBas2FrmEntity } from './company-role-bas-2frm-entity.interface';
import { ICompanyTransheaderEntity } from './company-transheader-entity.interface';
import { ICompanyUrlEntity } from './company-url-entity.interface';
import { ICompanyYearEntity } from './company-year-entity.interface';
import { ICompanyCreditorEntity } from './company-creditor-entity.interface';
import { ICompanyDebtorEntity } from './company-debtor-entity.interface';
import { IRubricCategory2CompanyEntity } from './rubric-category-2company-entity.interface';
import { ITelephoneNumberEntity } from './telephone-number-entity.interface';
import { ITrsConfigEntity } from './trs-config-entity.interface';

export interface ICompanyEntityGenerated  {
  AddressDto?: IAddressEntity;
  AddressFk?: number;
  BillingSchemaFk?: number;
  BlobsEntity?: IBlobsEntity;
  BlobsFk?: number;
  BusinessPartnerFk?: number;
  CalendarFk?: number;
  ClerkFk?: number;
  Code?: string;
  Companies?: Array<ICompanyEntity>;
  Company2BasClerkEntities?: Array<ICompany2BasClerkEntity>;
  Company2costCodeEntities?: Array<ICompany2CostCodeEntity>;
  Company2prjGroupEntities?: Array<ICompany2PrjGroupEntity>;
  Company2textModuleEntities?: Array<ICompany2TextModuleEntity>;
  CompanyChildren?: Array<ICompanyEntity>;
  CompanyFk?: number;
  CompanyName?: string;
  CompanyName2?: string;
  CompanyName3?: string;
  CompanyNumberEntities?: Array<ICompanyNumberEntity>;
  CompanyParent?: ICompanyEntity;
  CompanyRoleBas2frmEntities?: Array<ICompanyRoleBas2FrmEntity>;
  CompanyTransheaderEntities?: Array<ICompanyTransheaderEntity>;
  CompanyTypeFk?: number;
  CompanyUrlEntities?: Array<ICompanyUrlEntity>;
  CompanyYearEntities?: Array<ICompanyYearEntity>;
  CompanycreditorEntities?: Array<ICompanyCreditorEntity>;
  CompanydebtorEntities?: Array<ICompanyDebtorEntity>;
  ContextFk?: number;
  CountryFk?: number;
  CrefoNo?: string;
  CurrencyFk?: number;
  DefectContextFk?: number;
  DunsNo?: string;
  Email?: string;
  EquipmentContextFk?: number;
  EquipmentDivisionFk?: number;
  ExternalCode?: string;
  HasChildren?: boolean;
  HsqContextFk?: number;
  Id?: number;
  Internet?: string;
  IsCalculateOverGross?: boolean;
  IsLive?: boolean;
  IsRestrictedToProfitCenter?: boolean;
  IsRibArchive?: boolean;
  IsSequenceBasedOnProfitCenter?: boolean;
  LanguageFk?: number;
  LedgerContextFk?: number;
  LineItemContextFk?: number;
  LoginAllowed?: boolean;
  LogisticContextFk?: number;
  ModuleContextFk?: number;
  PaymentTermFiFk?: number;
  PaymentTermPaFk?: number;
  PriceConditionFk?: number;
  Profitcenter?: string;
  ProjectContextFk?: number;
  PrrMethodFk?: number;
  ResourceContextFk?: number;
  RubricCategory2companyEntities?: Array<IRubricCategory2CompanyEntity>;
  SchedulingContextFk?: number;
  SearchPattern?: string;
  Signatory?: string;
  SubledgerContextFk?: number;
  TaxCodeFk?: number;
  TaxNo?: string;
  TelefaxPattern?: string;
  TelephoneNumberDto?: ITelephoneNumberEntity;
  TelephoneNumberFk?: number;
  TelephoneNumberTelefaxDto?: ITelephoneNumberEntity;
  TelephonePattern?: string;
  TelephoneTelefaxFk?: number;
  TextModuleContextFk?: number;
  TimesheetContextFk?: number;
  TrsPrjConfigEntities?: Array<ITrsConfigEntity>;
  UserDefined1?: string;
  UserDefined2?: string;
  UserDefined3?: string;
  UserDefined4?: string;
  UserDefined5?: string;
  ValidFrom?: string;
  ValidTo?: string;
  VatNo?: string;
}
