/*
 * Copyright(c) RIB Software GmbH
 */

import { ICompanyNumberEntity } from './company-number-entity.interface';

export interface INumberSequenceEntityGenerated {
  CharStartvalue?: string;
  ChartEndvalue?: string;
  ChartLastvalue?: string;
  CompanyNumberEntities?: Array<ICompanyNumberEntity>;
  EndValue?: number;
  EntityId?: string;
  HeaderId?: number;
  Id?: number;
  IncrementValue?: number;
  IsAutogenerated?: boolean;
  IsDateDriven?: boolean;
  IsDefault?: boolean;
  IsLive?: boolean;
  IsNumeric?: boolean;
  LastValue?: number;
  NumberSequenceFk?: number;
  PeriodDate?: string;
  SequenceName?: string;
  SequenceTypeFk?: number;
  Sorting?: number;
  StartValue?: number;
}
