/*
 * Copyright(c) RIB Software GmbH
 */

import { IEntityBase, IEntityIdentification } from '@libs/platform/common';

export interface IBasicsCustomizeNumberSequenceEntity extends IEntityBase, IEntityIdentification {
	SequenceName: string;
	Sorting: number;
	IsDefault: boolean;
	StartValue: number;
	MaxValue: number;
	LastValue: number;
	IncrementValue: number;
	IsLive: boolean;
	HeaderId: number;
	EntityId: string;
	IsNumeric: boolean;
	CharStartvalue: string;
	ChartEndvalue: string;
	ChartLastvalue: string;
	Isautogenerated: boolean;
	Perioddate: Date | string;
	CodegensequenceTypeFk: number;
	NumberSequenceFk: number;
	Isdatedriven: boolean;
}
