/*
 * Copyright(c) RIB Software GmbH
 */

import { EntityInfo } from '@libs/ui/business-base';
import { PpsAccountingRulesetDataService } from '../services/pps-accounting-ruleset-data.service';
import { IRuleSetEntity } from './entities/ruleset-entity.interface';
import { prefixAllTranslationKeys } from '@libs/platform/common';


export const PPS_ACCOUNTING_RULESET_ENTITY_INFO: EntityInfo = EntityInfo.create<IRuleSetEntity>({
	grid: {
		title: { key: 'productionplanning.accounting.ruleSet.listTitle' },
		containerUuid: 'fcdf2e62fb8848bc99dd1a52fdbdf47f',
	},
	form: {
		title: { key: 'productionplanning.accounting.ruleSet.detailTitle' },
		containerUuid: '8995c131011941258ff7bde43ab47773',
	},
	dataService: ctx => ctx.injector.get(PpsAccountingRulesetDataService),
	dtoSchemeId: { moduleSubModule: 'ProductionPlanning.Accounting', typeName: 'RuleSetDto' },
	permissionUuid: 'fcdf2e62fb8848bc99dd1a52fdbdf47f',
	layoutConfiguration: {
		overloads:{
			AutoGenerated: {
				readonly: true
			}
		},
		labels: {
			...prefixAllTranslationKeys('cloud.common.', {
				Description: {key: 'entityDescription', text: '*Description'},
				IsLive: {key: 'entityIsLive', text: '*Active'},
				Comment: {key: 'entityComment', text: '*Comment'},
			}),
			...prefixAllTranslationKeys('productionplanning.accounting.', {
				AutoGenerated: {key: 'ruleSet.autoGenerated', text: '*Autogenerated'},
			}),
		}
	}
});