/*
 * Copyright(c) RIB Software GmbH
 */

export const CompareFields = {
	cost: 'Cost',
	unitRate: 'UnitRate',
	unitRateFrom: 'UnitRateFrom',
	unitRateTo: 'UnitRateTo',
	urBreakdown1: 'Urb1',
	urBreakdown2: 'Urb2',
	urBreakdown3: 'Urb3',
	urBreakdown4: 'Urb4',
	urBreakdown5: 'Urb5',
	urBreakdown6: 'Urb6',
	price: 'Price',
	priceOc: 'PriceOc',
	discountPercentIT: 'DiscountPercentIt',         // Discount %IT (only for Level 1-9, Root)
	discount: 'Discount',                           // Discount ABS.IT (only for Level 1-9, Root)
	discountPercent: 'DiscountPercent',             // Discount % UR (for Position)
	discountedPrice: 'DiscountedPrice',
	discountedPriceOc: 'DiscountedPriceOc',
	discountedUnitPrice: 'DiscountedUnitprice',     // note: lower case
	discountAbsolute: 'DiscountAbsolute',
	discountAbsoluteOc: 'DiscountAbsoluteOc',
	discountAbsoluteGross: 'DiscountAbsoluteGross',
	discountAbsoluteGrossOc: 'DiscountAbsoluteGrossOc',
	discountComment: 'DiscountComment',
	finalPrice: 'Finalprice',                       // note: lower case
	rank: 'Rank',
	percentage: 'Percentage',
	commentContractor: 'CommentContractor',         // bidder comments
	commentClient: 'CommentClient',                 // client comments
	quantity: 'Quantity',                           // quantity
	prcItemEvaluationFk: 'PrcItemEvaluationFk',     // item evaluation
	bidderComments: 'BidderComments',
	userDefined1: 'Userdefined1',
	userDefined2: 'Userdefined2',
	userDefined3: 'Userdefined3',
	userDefined4: 'Userdefined4',
	userDefined5: 'Userdefined5',
	quoteUserDefined1: 'UserDefined1',
	quoteUserDefined2: 'UserDefined2',
	quoteUserDefined3: 'UserDefined3',
	quoteUserDefined4: 'UserDefined4',
	quoteUserDefined5: 'UserDefined5',
	alternativeBid: 'BasItemType85Fk',
	finalPriceOc: 'FinalpriceOc',
	itemTotal: 'ItemTotal',
	itemTotalOc: 'ItemTotalOc',
	lumpsumPrice: 'LumpsumPrice',
	isLumpsum: 'IsLumpsum',
	boqTotalRank: 'BoqTotalRank',
	remark: 'Remark',
	absoluteDifference: 'AbsoluteDifference',
	externalCode: 'ExternalCode',
	priceGross: 'Pricegross',
	priceGrossOc: 'PricegrossOc',
	finalGross: 'Finalgross',
	finalGrossOc: 'FinalgrossOc',
	notSubmitted: 'NotSubmitted',
	included: 'Included',
	budgetTotal: 'BudgetTotal',
	uomFk: 'UomFk',
	factor: 'Factor',
	extraIncrement: 'ExtraIncrement',
	extraIncrementOc: 'ExtraIncrementOc',
	exQtnIsEvaluated: 'ExQtnIsEvaluated',
	discountOc: 'DiscountOc',
	prjChangeFk: 'PrjChangeFk',
	prjChangeStatusFk: 'PrjChangeStatusFk',
	generals: 'Generals',
	characteristics: 'Characteristics',
	factoredTotalPrice: 'FactoredTotalPrice',
	co2Project: 'Co2Project',
	co2ProjectTotal: 'Co2ProjectTotal',
	co2Source: 'Co2Source',
	co2SourceTotal: 'Co2SourceTotal',
	paymentTermPaFk: 'PaymentTermPaFk',
	paymentTermFiFk: 'PaymentTermFiFk',
	discountSplit: 'DiscountSplit',
	discountSplitOc: 'DiscountSplitOc',
	totalNoDiscount: 'TotalNoDiscount',
	totalOcNoDiscount: 'TotalOcNoDiscount',
	priceExtra: 'PriceExtra',
	priceExtraOc: 'PriceExtraOc',
	priceUnit: 'PriceUnit',
	totalPrice: 'TotalPrice',
	totalPriceOc: 'TotalPriceOc',
	total: 'Total',
	prcPriceConditionFk: 'PrcPriceConditionFk',
	leadTime: 'LeadTime',
	leadTimeExtra: 'LeadTimeExtra',
	totalOC: 'TotalOc',
	priceOCGross: 'PriceOCGross',
	totalPriceGross: 'TotalPriceGross',
	totalPriceOCGross: 'TotalPriceOCGross',
	totalGross: 'TotalGross',
	totalOCGross: 'TotalOCGross',
	factoredQuantity: 'FactoredQuantity',
	isFreeQuantity: 'IsFreeQuantity',
	budgetPerUnit: 'BudgetPerUnit',
	factorPriceUnit: 'FactorPriceUnit',
	code: 'Code',
	description: 'Description',
	quoteDate: 'DateQuoted',
	receiveDate: 'DateReceived',
	priceFixingDate: 'DatePricefixing',
	exchangeRate: 'ExchangeRate',
	currency: 'CurrencyFk',
	incoterms: 'IncotermFk',
	paymentTermPA: 'PaymentTermPaFk',
	paymentTermPADesc: 'PaymentTermPaDesc',
	paymentTermFI: 'PaymentTermFiFk',
	paymentTermFIDesc: 'PaymentTermFiDesc',
	quoteStatus: 'StatusFk',
	quoteVersion: 'QuoteVersion',
	evaluationRank: 'EvaluationRank',
	evaluationResult: 'EvaluationResult',
	grandTotalRank: 'GrandTotalRank',
	overallDiscount: 'OverallDiscount',
	overallDiscountOc: 'OverallDiscountOc',
	overallDiscountPercent: 'OverallDiscountPercent',
	userDefinedDate01: 'UserDefinedDate01',
	turnover: 'Turnover',
	avgEvaluationA: 'AvgEvaluationA',
	avgEvaluationB: 'AvgEvaluationB',
	avgEvaluationC: 'AvgEvaluationC',
	avgEvaluationRank: 'AvgEvaluationRank',
	evaluatedTotal: 'EvaluatedTotal',
	offeredTotal: 'OfferedTotal',
	projectChange: 'PrjChangeFk',
	projectChangeStatus: 'PrjChangeStatusFk',
	netTotal: 'NetTotal',
	earlyPaymentDiscount: 'EarlyPaymentDiscount',
	subTotal: 'SubTotal',
	vat: 'Vat',
	runningTotal: 'RunningTotal',
	discountBasis: 'AmountDiscountBasis',
	discountBasisOc: 'AmountDiscountBasisOc',
	percentDiscount: 'PercentDiscount',
	discountAmount: 'AmountDiscount',
	discountAmountOc: 'AmountDiscountOc',
	quantityAdj: 'QuantityAdj',
	quantityAdjDetail: 'QuantityAdjDetail',
	charge: 'Charge',
	chargeOc: 'ChargeOc'
};