/*
 * $Id$
 * Copyright(c) RIB Software GmbH
 */


import { IEntityBase } from '@libs/platform/common';
import { ICompanyNumberEntity } from './company-number-entity.interface';


export interface INumberSequenceEntity extends IEntityBase {
	CharStartvalue?: string | null;
	ChartEndvalue?: string | null;
	ChartLastvalue?: string | null;
	CompanyNumberEntities?: ICompanyNumberEntity[] | null;
	EndValue?: number | null;
	EntityId?: string | null;
	HeaderId?: number | null;
	Id?: number | null;
	IncrementValue?: number | null;
	IsAutogenerated?: boolean | null;
	IsDateDriven?: boolean | null;
	IsDefault?: boolean | null;
	IsLive?: boolean | null;
	IsNumeric?: boolean | null;
	LastValue?: number | null;
	NumberSequenceFk?: number | null;
	PeriodDate?: string | null;
	SequenceName?: string | null;
	SequenceTypeFk?: number | null;
	Sorting?: number | null;
	StartValue?: number | null;
}
