/*
 * $Id$
 * Copyright(c) RIB Software GmbH
 */

export interface IPpsLogReportVEntityGenerated {
	/*
	 * AutoGenerated
	 */
	AutoGenerated: boolean;

	/*
	 * ColumnId
	 */
	ColumnId?: number | null;

	/*
	 * ColumnName
	 */
	ColumnName?: string | null;

	/*
	 * Date
	 */
	Date: string;

	/*
	 * Id
	 */
	Id: number;

	/*
	 * NewValue
	 */
	NewValue?: string | null;

	/*
	 * NewValueDescription
	 */
	NewValueDescription?: string | null;

	/*
	 * OldValue
	 */
	OldValue?: string | null;

	/*
	 * OldValueDescription
	 */
	OldValueDescription?: string | null;

	/*
	 * ParentId
	 */
	ParentId?: number | null;

	/*
	 * PpsEntityDescription
	 */
	PpsEntityDescription?: string | null;

	/*
	 * PpsEntityFk
	 */
	PpsEntityFk: number;

	/*
	 * PpsItemAndLogId
	 */
	PpsItemAndLogId?: string | null;

	/*
	 * PpsItemCode
	 */
	PpsItemCode?: string | null;

	/*
	 * PpsItemId
	 */
	PpsItemId?: number | null;

	/*
	 * PpsLogConfigFk
	 */
	PpsLogConfigFk?: number | null;

	/*
	 * PpsLogReasonFk
	 */
	PpsLogReasonFk?: number | null;

	/*
	 * Reason
	 */
	Reason?: string | null;

	/*
	 * RecordCode
	 */
	RecordCode?: string | null;

	/*
	 * RecordDescription
	 */
	RecordDescription?: string | null;

	/*
	 * RecordId
	 */
	RecordId: number;

	/*
	 * RecordType
	 */
	RecordType?: string | null;

	/*
	 * Remark
	 */
	Remark?: string | null;

	/*
	 * TableId
	 */
	TableId?: number | null;

	/*
	 * Updater
	 */
	Updater?: string | null;

	/*
	 * WhoIsr
	 */
	WhoIsr: number;
}
