/**
 * Copyright(c) RIB Software GmbH
 */

export interface ITaskList {
	ActionId: string,
	BusinesspartnerId?: number,
	BusinesspartnerName1?: number,
	BusinesspartnerName2?: number,
	BusinesspartnerName3?: number,
	BusinesspartnerName4?: number,
	Clerk: string | object,
	Comment: string,
	Context: string,
	Description: string,
	ClerkFamilyName: string,
	ClerkFirstName: string,
	Endtime: string,
	EndtimeFormatted: string,
	EntityIdList: number[],
	IsEntityListLoaded: boolean,
	ExecuteCondition: string,
	FrmUserIssuerFk: number,
	FrmUserProgressByFk: number,
	Id: number,
	IdInTemplate: number,
	Input: string,
	IsRunning: boolean,
	IsNotification: boolean,
	Lifetime: number,
	LifetimeIcon: string,
	Output: string,
	OwnerDescription: string,
	OwnerId: number,
	OwnerName: string,
	OwnerIcon: string,
	PriorityId: number,
	PriorityIcon: string,
	ProgressById: number,
	Result: string,
	Hidden: boolean,
	Started: string,
	StartedFormatted: string,
	Status: number,
	TemplateDescription: string,
	Transitions: string,
	UserDefined1: string,
	UserDefined2: string,
	UserDefined3: string,
	UserDefined4: string,
	UserDefined5: string,
	UserDefinedDate1: string,
	UserDefinedDate2: string,
	UserDefinedDate3: string,
	UserDefinedDate4: string,
	UserDefinedDate5: string,
	UserDefinedMoney1: number,
	UserDefinedMoney2: number,
	UserDefinedMoney3: number,
	UserDefinedMoney4: number,
	UserDefinedMoney5: number,
	WorkflowInstanceId: number
}