/*
 * $Id$
 * Copyright(c) RIB Software GmbH
 */
export const menu = {
	cssClass: 'layout-bar',
	currentButton: null,
	initOnce: true,
	items: [
		{
			caption: 'radio group caption',
			isDisplayed: true,
			type: 'sublist',
			captionString:'',
			id:'',
			list: {
				activeValue: 'layout24',
				cssClass: 'radio-group',
				level: 1,
				showTitles: true,
				items: [
					{
						caption: 'Layout 0',
						cssClass: 'item layout-icons ico-layout0',
						id: 'layout0',
						isDisplayed: true,
						type: 'radio',
						value: 'layout0',
					},
					{
						caption: 'Layout 1',
						cssClass: 'item layout-icons ico-layout1',
						id: 'layout1',
						isDisplayed: true,
						type: 'radio',
						value: 'layout1',
					},
					{
						caption: 'Layout 2',
						cssClass: 'item layout-icons ico-layout2',
						id: 'layout2',
						isDisplayed: true,
						type: 'radio',
						value: 'layout2',
					},
					{
						caption: 'Layout 3',
						cssClass: 'item layout-icons ico-layout3',
						id: 'layout3',
						isDisplayed: true,
						type: 'radio',
						value: 'layout3',
					},
					{
						caption: 'Layout 4',
						cssClass: 'item layout-icons ico-layout4',
						id: 'layout4',
						isDisplayed: true,
						type: 'radio',
						value: 'layout4',
					},
					{
						caption: 'Layout 5',
						cssClass: 'item layout-icons ico-layout5',
						id: 'layout5',
						isDisplayed: true,
						type: 'radio',
						value: 'layout5',
					},
					{
						caption: 'Layout 6',
						cssClass: 'item layout-icons ico-layout6',
						id: 'layout6',
						isDisplayed: true,
						type: 'radio',
						value: 'layout6',
					},
					{
						caption: 'Layout 7',
						cssClass: 'item layout-icons ico-layout7',
						id: 'layout7',
						isDisplayed: true,
						type: 'radio',
						value: 'layout7',
					},
					{
						caption: 'Layout 8',
						cssClass: 'item layout-icons ico-layout8',
						id: 'layout8',
						isDisplayed: true,
						type: 'radio',
						value: 'layout8',
					},
					{
						caption: 'Layout 9',
						cssClass: 'item layout-icons ico-layout9',
						id: 'layout9',
						isDisplayed: true,
						type: 'radio',
						value: 'layout9',
					},
					{
						caption: 'Layout 10',
						cssClass: 'item layout-icons ico-layout10',
						id: 'layout10',
						isDisplayed: true,
						type: 'radio',
						value: 'layout10',
					},
					{
						caption: 'Layout 11',
						cssClass: 'item layout-icons ico-layout11',
						id: 'layout11',
						isDisplayed: true,
						type: 'radio',
						value: 'layout11',
					},
					{
						caption: 'Layout 12',
						cssClass: 'item layout-icons ico-layout12',
						id: 'layout12',
						isDisplayed: true,
						type: 'radio',
						value: 'layout12',
					},
					{
						caption: 'Layout 13',
						cssClass: 'item layout-icons ico-layout13',
						id: 'layout13',
						isDisplayed: true,
						type: 'radio',
						value: 'layout13',
					},
					{
						caption: 'Layout 14',
						cssClass: 'item layout-icons ico-layout14',
						id: 'layout14',
						isDisplayed: true,
						type: 'radio',
						value: 'layout14',
					},
					{
						caption: 'Layout 15',
						cssClass: 'item layout-icons ico-layout15',
						id: 'layout15',
						isDisplayed: true,
						type: 'radio',
						value: 'layout15',
					},
					{
						caption: 'Layout 16',
						cssClass: 'item layout-icons ico-layout16',
						id: 'layout16',
						isDisplayed: true,
						type: 'radio',
						value: 'layout16',
					},
					{
						caption: 'Layout 17',
						cssClass: 'item layout-icons ico-layout17',
						id: 'layout17',
						isDisplayed: true,
						type: 'radio',
						value: 'layout17',
					},
					{
						caption: 'Layout 18',
						cssClass: 'item layout-icons ico-layout18',
						id: 'layout18',
						isDisplayed: true,
						type: 'radio',
						value: 'layout18',
					},
					{
						caption: 'Layout 19',
						cssClass: 'item layout-icons ico-layout19',
						id: 'layout19',
						isDisplayed: true,
						type: 'radio',
						value: 'layout19',
					},
					{
						caption: 'Layout 20',
						cssClass: 'item layout-icons ico-layout20',
						id: 'layout20',
						isDisplayed: true,
						type: 'radio',
						value: 'layout20',
					},
					{
						caption: 'Layout 21',
						cssClass: 'item layout-icons ico-layout21',
						id: 'layout21',
						isDisplayed: true,
						type: 'radio',
						value: 'layout21',
					},
					{
						caption: 'Layout 22',
						cssClass: 'item layout-icons ico-layout22',
						id: 'layout22',
						isDisplayed: true,
						type: 'radio',
						value: 'layout22',
					},
					{
						caption: 'Layout 23',
						cssClass: 'item layout-icons ico-layout23',
						id: 'layout23',
						isDisplayed: true,
						type: 'radio',
						value: 'layout23',
					},
					{
						caption: 'Layout 24',
						cssClass: 'item layout-icons ico-layout24',
						id: 'layout24',
						isDisplayed: true,
						type: 'radio',
						value: 'layout24',
					},
					{
						caption: 'Layout 25',
						cssClass: 'item layout-icons ico-layout25',
						id: 'layout25',
						isDisplayed: true,
						type: 'radio',
						value: 'layout25',
					}
				],
			},
		},
	],
	level: 0,
	refreshVersion: 0,
	rootPath: 'layoutBar',
	showImages: true,
	showTitles: true,
	sublist: false,
	version: 0,
};
