/*
 * Copyright(c) RIB Software GmbH
 */

import { IContactEntity } from '../contact';

export class BusinessPartnerLookupVEntity {
	public BpIsExisted!: boolean;
	public SupplierId?: number | null;
	public AvgEvaluationA!: number;
	public AvgEvaluationB!: number;
	public AvgEvaluationC!: number;
	public IsFrameWork!: number;
	public CountEvaluationA!: number;
	public CountEvaluationB!: number;
	public CountEvaluationC!: number;
	public BusinessPartnerName1?: string;
	public BusinessPartnerName2?: string;
	public BusinessPartnerName3?: string;
	public BusinessPartnerName4?: string;
	public Email?: string;
	public MatchCode?: string;
	public IsLive!: boolean;
	public Avaid?: number;
	public Description?: string;
	public Street?: string;
	public ZipCode?: string;
	public City?: string;
	public County?: string;
	public Country?: string;
	public Iso2?: string;
	public SubsidiaryFk?: number;
	public AddressLine?: string;
	public TelephoneNumber1?: string;
	public FaxNumber?: string;
	public Telephonenumber2?: string;
	public Mobile?: string;
	public CountryFk?: number;
	public IsNationWide?: boolean;
	public StatusDescriptionTranslateInfo?: string;
	public Status2DescriptionTranslateInfo?: string;
	public Icon?: number;
	public Status2Icon?: number;
	public Userdefined1?: string;
	public BpdStatusFk!: number;
	public Userdefined2?: string;
	public Userdefined3?: string;
	public Userdefined4?: string;
	public Userdefined5?: string;
	public VatNo?: string;
	public TaxNo?: string;
	public Longitude?: number;
	public Latitude?: number;
	public BasCommunicationChannelFk?: number;
	public Internet?: string;
	public CrefoNo?: string;
	public BedirektNo?: string;
	public DunsNo?: string;
	public TradeRegister?: string;
	public TradeRegisterNo?: string;
	public CraftCooperative?: string;
	public CraftCooperativeType?: string;
	public CustomerAbcFk?: number;
	public CustomerSectorFk?: number;
	public CustomerStatusFk?: number;
	public CustomerAbc?: string;
	public CustomerGroupFk?: number;
	public CustomerSector?: string;
	public LegalFormFk?: number;
	public CustomerStatus?: string;
	public CreditstandingFk?: number;
	public CustomerGroup?: string;
	public RemarkMarketing?: string;
	public LegalForm?: string;
	public Remark1?: string;
	public Creditstanding?: string;
	public Remark2?: string;
	public RefValue1?: string;
	public RefValue2?: string;
	public TradeName?: string;
	public BpdStatus2Fk?: number;
	public PrcIncotermFk?: number;
	public Code?: string;
	public LanguageFk?: number;
	public LanguageDesc?: string;
	public TaxOfficeCode?: string;
	public HasFrameworkAgreement!: boolean;
	public RubricCategoryFk?: number;
	public CompanyFk!: number;
	public ClerkFk?: number;
	public Salutation?: string;
	public CustomerBranchFk?: number;
	public CraftcooperativeDate?: string;
	public TitleFk!: number;
	public CountryVatFk?: number;
	public VatNoEu?: string;
	public Inserted?: string;
	public Updated?: string;
	public CreateUserName?: string;
	public UpdateUserName?: string;
	public TradeRegisterDate?: string;
	public ActiveFrmkCont?: number;
	public ContactDtos: IContactEntity[] = [];
}