import { IDescriptionInfo, IEntityBase, IEntityIdentification } from '@libs/platform/common';

export interface ControllingUnitEntityInterface extends IEntityBase, IEntityIdentification{
	Id: number,
	ControllingunitstatusFk: number;
	ControllingunitFk? : number;
	ControltemplateFk? : number;
	ControltemplateUnitFk? : number;
	ContextFk : number;
	Code : string;
	DescriptionInfo : IDescriptionInfo;
	ControllingCatFk : number;
	ProjectFk? : number;
	Quantity? : number;
	UomFk : number;
	StockFk? : number;
	EtmPlantFk? : number;
	IsBillingElement : boolean;
	IsAccountingElement : boolean;
	IsPlanningElement : boolean;
	IsTimekeepingElement : boolean;
	IsAssetmanagement : boolean;
	IsStockmanagement : boolean;
	IsPlantmanagement : boolean;
	IsIntercompany : boolean;
	PlannedStart? : string;
	PlannedEnd? : string;
	PlannedDuration: number;
	Assignment01: string;
	ControllingGrpDetail01Fk? : number;
	Assignment02: string;
	ControllingGrpDetail02Fk?: number;
	Assignment03: string;
	ControllingGrpDetail03Fk?: number;
	Assignment04: string;
	ControllingGrpDetail04Fk?: number;
	Assignment05: string;
	ControllingGrpDetail05Fk?: number;
	Assignment06: string;
	ControllingGrpDetail06Fk?: number;
	Assignment07: string;
	ControllingGrpDetail07Fk?: number;
	Assignment08: string;
	ControllingGrpDetail08Fk?: number;
	Assignment09: string;
	ControllingGrpDetail09Fk?: number;
	Assignment10: string;
	ControllingGrpDetail10Fk?: number;
	CommentText: string;
	UserDefined1: string;
	UserDefined2: string;
	UserDefined3: string;
	UserDefined4: string;
	UserDefined5: string;
	Budget: number;
	IsFixedBudget: boolean;
	IsDefault: boolean;
	BudgetDifference? : number;
	EstimateCost? : number;
	BudgetCostDiff? : number;
	CompanyFk : number;
	ClerkFk? : number;
	CompanyResponsibleFk : number;
	ContrFormulaPropDefFk? : number;
}