/**
 * $Id$
 * Copyright(c) RIB Software GmbH
 */
import { TestBed } from '@angular/core/testing';
import { HttpClientModule } from '@angular/common/http';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';

import { PlatformReportLanguageItemService } from './report-language-item.service';

const Language_DATA = {
	showImages: true,
	showTitles: true,
	type: 1,
	items: [
		{
			Id: 1,
			Sorting: 10,
			Description: 'English',
			Language: 'en',
			Culture: 'en-gb',
			id: 1,
			cssClass: 'btn-default',
			caption: 'English',
			toolTip: 'English',
			iconClass: 'control-icons ico-en',
			type: 'item',
		},
		{
			Id: 3,
			Sorting: 10,
			Description: 'English (US)',
			Language: 'en-us',
			Culture: 'en-us',
			id: 3,
			cssClass: 'btn-default',
			caption: 'English (US)',
			toolTip: 'English (US)',
			iconClass: 'control-icons ico-en-us',
			type: 'item',
		},
		{
			Id: 2,
			Sorting: 20,
			Description: 'German',
			Language: 'de',
			Culture: 'de-de',
			id: 2,
			cssClass: 'btn-default',
			caption: 'German',
			toolTip: 'German',
			iconClass: 'control-icons ico-de',
			type: 'item',
		},
		{
			Id: 24,
			Sorting: 20,
			Description: 'German (Swiss)',
			Language: 'de-ch',
			Culture: 'de-ch',
			id: 24,
			cssClass: 'btn-default',
			caption: 'German (Swiss)',
			toolTip: 'German (Swiss)',
			iconClass: 'control-icons ico-de-ch',
			type: 'item',
		},
		{
			Id: 4,
			Sorting: 40,
			Description: 'Spanish',
			Language: 'es',
			Culture: 'es-es',
			id: 4,
			cssClass: 'btn-default',
			caption: 'Spanish',
			toolTip: 'Spanish',
			iconClass: 'control-icons ico-es',
			type: 'item',
		},
		{
			Id: 5,
			Sorting: 50,
			Description: 'Finnish',
			Language: 'fi',
			Culture: 'fi-fi',
			id: 5,
			cssClass: 'btn-default',
			caption: 'Finnish',
			toolTip: 'Finnish',
			iconClass: 'control-icons ico-fi',
			type: 'item',
		},
		{
			Id: 6,
			Sorting: 60,
			Description: 'French',
			Language: 'fr',
			Culture: 'fr-fr',
			id: 6,
			cssClass: 'btn-default',
			caption: 'French',
			toolTip: 'French',
			iconClass: 'control-icons ico-fr',
			type: 'item',
		},
		{
			Id: 25,
			Sorting: 60,
			Description: 'French (Swiss)',
			Language: 'fr-ch',
			Culture: 'fr-ch',
			id: 25,
			cssClass: 'btn-default',
			caption: 'French (Swiss)',
			toolTip: 'French (Swiss)',
			iconClass: 'control-icons ico-fr-ch',
			type: 'item',
		},
		{
			Id: 7,
			Sorting: 70,
			Description: 'Dutch',
			Language: 'nl',
			Culture: 'nl-nl',
			id: 7,
			cssClass: 'btn-default',
			caption: 'Dutch',
			toolTip: 'Dutch',
			iconClass: 'control-icons ico-nl',
			type: 'item',
		},
		{
			Id: 8,
			Sorting: 80,
			Description: 'Russian',
			Language: 'ru',
			Culture: 'ru-ru',
			id: 8,
			cssClass: 'btn-default',
			caption: 'Russian',
			toolTip: 'Russian',
			iconClass: 'control-icons ico-ru',
			type: 'item',
		},
		{
			Id: 9,
			Sorting: 90,
			Description: 'Chinese',
			Language: 'zh',
			Culture: 'zh-cn',
			id: 9,
			cssClass: 'btn-default',
			caption: 'Chinese',
			toolTip: 'Chinese',
			iconClass: 'control-icons ico-zh',
			type: 'item',
		},
		{
			Id: 23,
			Sorting: 90,
			Description: 'Chinese (Traditional)',
			Language: 'zh-hant',
			Culture: 'zh-hant',
			id: 23,
			cssClass: 'btn-default',
			caption: 'Chinese (Traditional)',
			toolTip: 'Chinese (Traditional)',
			iconClass: 'control-icons ico-zh-hant',
			type: 'item',
		},
		{
			Id: 10,
			Sorting: 100,
			Description: 'Italian',
			Language: 'it',
			Culture: 'it-it',
			id: 10,
			cssClass: 'btn-default',
			caption: 'Italian',
			toolTip: 'Italian',
			iconClass: 'control-icons ico-it',
			type: 'item',
		},
		{
			Id: 26,
			Sorting: 100,
			Description: 'Italian (Swiss)',
			Language: 'it-ch',
			Culture: 'it-ch',
			id: 26,
			cssClass: 'btn-default',
			caption: 'Italian (Swiss)',
			toolTip: 'Italian (Swiss)',
			iconClass: 'control-icons ico-it-ch',
			type: 'item',
		},
		{
			Id: 11,
			Sorting: 110,
			Description: 'Czech',
			Language: 'cs',
			Culture: 'cs-cz',
			id: 11,
			cssClass: 'btn-default',
			caption: 'Czech',
			toolTip: 'Czech',
			iconClass: 'control-icons ico-cs',
			type: 'item',
		},
		{
			Id: 12,
			Sorting: 120,
			Description: 'Polish',
			Language: 'pl',
			Culture: 'pl-pl',
			id: 12,
			cssClass: 'btn-default',
			caption: 'Polish',
			toolTip: 'Polish',
			iconClass: 'control-icons ico-pl',
			type: 'item',
		},
		{
			Id: 13,
			Sorting: 130,
			Description: 'Swedish',
			Language: 'sv',
			Culture: 'sv-se',
			id: 13,
			cssClass: 'btn-default',
			caption: 'Swedish',
			toolTip: 'Swedish',
			iconClass: 'control-icons ico-sv',
			type: 'item',
		},
		{
			Id: 14,
			Sorting: 140,
			Description: 'Norwegian',
			Language: 'nb',
			Culture: 'nb-no',
			id: 14,
			cssClass: 'btn-default',
			caption: 'Norwegian',
			toolTip: 'Norwegian',
			iconClass: 'control-icons ico-nb',
			type: 'item',
		},
		{
			Id: 15,
			Sorting: 150,
			Description: 'Lithuanian',
			Language: 'lt',
			Culture: 'lt-lt',
			id: 15,
			cssClass: 'btn-default',
			caption: 'Lithuanian',
			toolTip: 'Lithuanian',
			iconClass: 'control-icons ico-lt',
			type: 'item',
		},
		{
			Id: 16,
			Sorting: 160,
			Description: 'Japanese',
			Language: 'ja',
			Culture: 'ja-jp',
			id: 16,
			cssClass: 'btn-default',
			caption: 'Japanese',
			toolTip: 'Japanese',
			iconClass: 'control-icons ico-ja',
			type: 'item',
		},
		{
			Id: 17,
			Sorting: 170,
			Description: 'Portuguese',
			Language: 'pt',
			Culture: 'pt-pt',
			id: 17,
			cssClass: 'btn-default',
			caption: 'Portuguese',
			toolTip: 'Portuguese',
			iconClass: 'control-icons ico-pt',
			type: 'item',
		},
		{
			Id: 18,
			Sorting: 180,
			Description: 'Danish',
			Language: 'da',
			Culture: 'da-dk',
			id: 18,
			cssClass: 'btn-default',
			caption: 'Danish',
			toolTip: 'Danish',
			iconClass: 'control-icons ico-da',
			type: 'item',
		},
		{
			Id: 19,
			Sorting: 190,
			Description: 'Korean',
			Language: 'ko',
			Culture: 'ko-kr',
			id: 19,
			cssClass: 'btn-default',
			caption: 'Korean',
			toolTip: 'Korean',
			iconClass: 'control-icons ico-ko',
			type: 'item',
		},
		{
			Id: 20,
			Sorting: 200,
			Description: 'Vietnamese',
			Language: 'vi',
			Culture: 'vi-vn',
			id: 20,
			cssClass: 'btn-default',
			caption: 'Vietnamese',
			toolTip: 'Vietnamese',
			iconClass: 'control-icons ico-vi',
			type: 'item',
		},
		{
			Id: 21,
			Sorting: 210,
			Description: 'Thai',
			Language: 'th',
			Culture: 'th-th',
			id: 21,
			cssClass: 'btn-default',
			caption: 'Thai',
			toolTip: 'Thai',
			iconClass: 'control-icons ico-th',
			type: 'item',
		},
		{
			Id: 22,
			Sorting: 220,
			Description: 'Indonesian',
			Language: 'id',
			Culture: 'id-id',
			id: 22,
			cssClass: 'btn-default',
			caption: 'Indonesian',
			toolTip: 'Indonesian',
			iconClass: 'control-icons ico-id',
			type: 'item',
		},
		{
			Id: 27,
			Sorting: 230,
			Description: 'Romanian',
			Language: 'ro',
			Culture: 'ro-ro',
			id: 27,
			cssClass: 'btn-default',
			caption: 'Romanian',
			toolTip: 'Romanian',
			iconClass: 'control-icons ico-ro',
			type: 'item',
		},
		{
			Id: 28,
			Sorting: 240,
			Description: 'Hungarian',
			Language: 'hu',
			Culture: 'hu-hu',
			id: 28,
			cssClass: 'btn-default',
			caption: 'Hungarian',
			toolTip: 'Hungarian',
			iconClass: 'control-icons ico-hu',
			type: 'item',
		},
		{
			Id: 30,
			Sorting: 260,
			Description: 'Flemish',
			Language: 'nl-be',
			Culture: 'nl-be',
			id: 30,
			cssClass: 'btn-default',
			caption: 'Flemish',
			toolTip: 'Flemish',
			iconClass: 'control-icons ico-nl-be',
			type: 'item',
		},
	],
	activeValue: 7,
};

const LANG_DATA = {
	datalanguages: [
		{
			Id: 1,
			DescriptionInfo: {
				Description: 'English',
				DescriptionTr: 3,
				DescriptionModified: false,
				Translated: 'English',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'en',
			Sorting: 10,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2015-05-01T00:00:00Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 3943,
			Version: 13,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 6,
			DescriptionInfo: {
				Description: 'English (US)',
				DescriptionTr: 10860,
				DescriptionModified: false,
				Translated: 'English (US)',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'en-us',
			Sorting: 10,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2018-08-17T10:39:53.757Z',
			InsertedBy: 1,
			UpdatedAt: '2022-11-11T15:22:13.673Z',
			UpdatedBy: 1,
			Version: 4,
			Codefinance: null,
			FbLanguageFk: 1,
		},
		{
			Id: 2,
			DescriptionInfo: {
				Description: 'Deutsch',
				DescriptionTr: 4,
				DescriptionModified: false,
				Translated: 'Deutsch',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'de',
			Sorting: 20,
			IsDefault: true,
			Islive: true,
			InsertedAt: '2015-05-01T00:00:00Z',
			InsertedBy: 1,
			UpdatedAt: '2023-03-30T14:34:02.75Z',
			UpdatedBy: 1,
			Version: 8,
			Codefinance: 'CODEFIN-DE',
			FbLanguageFk: null,
		},
		{
			Id: 24,
			DescriptionInfo: {
				Description: 'German (Swiss)',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'German (Swiss)',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'de-ch',
			Sorting: 20,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2022-01-19T09:43:32.077Z',
			InsertedBy: 1,
			UpdatedAt: '2023-08-10T05:29:16.26Z',
			UpdatedBy: 5059,
			Version: 10,
			Codefinance: null,
			FbLanguageFk: 2,
		},
		{
			Id: 3,
			DescriptionInfo: {
				Description: 'Suomi',
				DescriptionTr: 5,
				DescriptionModified: false,
				Translated: 'Suomi',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'fi',
			Sorting: 30,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2015-05-01T00:00:00Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 34,
			Version: 11,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 4,
			DescriptionInfo: {
				Description: 'Русский',
				DescriptionTr: 6,
				DescriptionModified: false,
				Translated: 'Русский',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'ru',
			Sorting: 40,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2015-05-01T00:00:00Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 34,
			Version: 8,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 5,
			DescriptionInfo: {
				Description: 'Chinese',
				DescriptionTr: 7,
				DescriptionModified: false,
				Translated: 'Chinese',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'zh',
			Sorting: 50,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2015-05-01T00:00:00Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 170,
			Version: 5,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 23,
			DescriptionInfo: {
				Description: 'Chinese (Traditional)',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Chinese (Traditional)',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'zh-hant',
			Sorting: 50,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-10-26T07:56:13.427Z',
			InsertedBy: 1,
			UpdatedAt: '2022-11-11T15:22:13.833Z',
			UpdatedBy: 1,
			Version: 5,
			Codefinance: null,
			FbLanguageFk: 5,
		},
		{
			Id: 7,
			DescriptionInfo: {
				Description: 'Français',
				DescriptionTr: 10861,
				DescriptionModified: false,
				Translated: 'Français',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'fr',
			Sorting: 70,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2018-08-17T10:39:53.757Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 170,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 25,
			DescriptionInfo: {
				Description: 'French (Swiss)',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'French (Swiss)',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'fr-ch',
			Sorting: 70,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2022-02-11T15:07:28.927Z',
			InsertedBy: 1,
			UpdatedAt: '2022-11-11T15:22:13.84Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: 7,
		},
		{
			Id: 8,
			DescriptionInfo: {
				Description: 'Español',
				DescriptionTr: 10862,
				DescriptionModified: false,
				Translated: 'Español',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'es',
			Sorting: 80,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2018-05-24T00:00:00Z',
			InsertedBy: 1,
			UpdatedAt: '2022-12-28T15:19:06.023Z',
			UpdatedBy: 1,
			Version: 6,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 9,
			DescriptionInfo: {
				Description: 'Nederlands',
				DescriptionTr: 41,
				DescriptionModified: false,
				Translated: 'Nederlands',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'nl',
			Sorting: 90,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2018-08-17T10:39:53.757Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 170,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 10,
			DescriptionInfo: {
				Description: 'Italiano',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Italiano',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'it',
			Sorting: 100,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2019-03-07T18:36:06.687Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 11,
			Version: 6,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 26,
			DescriptionInfo: {
				Description: 'Italian (Swiss)',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Italian (Swiss)',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'it-ch',
			Sorting: 100,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2022-02-11T15:07:29.033Z',
			InsertedBy: 1,
			UpdatedAt: '2022-11-24T14:14:06.843Z',
			UpdatedBy: 2735,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: 10,
		},
		{
			Id: 11,
			DescriptionInfo: {
				Description: 'Czech',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Czech',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'cs',
			Sorting: 110,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2020-05-06T14:07:41.99Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 4,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 12,
			DescriptionInfo: {
				Description: 'Polish',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Polish',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'pl',
			Sorting: 120,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2020-05-06T14:07:41.99Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 4,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 13,
			DescriptionInfo: {
				Description: 'Swedish',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Swedish',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'sv',
			Sorting: 130,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2020-05-06T14:07:41.99Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 4,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 14,
			DescriptionInfo: {
				Description: 'Norwegian',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Norwegian',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'nb',
			Sorting: 140,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2020-05-06T14:07:41.99Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 4,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 15,
			DescriptionInfo: {
				Description: 'Lithuanian',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Lithuanian',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'lt',
			Sorting: 150,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2020-12-15T17:01:20.833Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1147,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 16,
			DescriptionInfo: {
				Description: 'Japanese',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Japanese',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'ja',
			Sorting: 160,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-06-14T11:23:01.723Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 17,
			DescriptionInfo: {
				Description: 'Portuguese',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Portuguese',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'pt',
			Sorting: 170,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-06-14T11:23:02.23Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 18,
			DescriptionInfo: {
				Description: 'Danish',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Danish',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'da',
			Sorting: 180,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-06-14T11:23:02.713Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 19,
			DescriptionInfo: {
				Description: 'Korean',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Korean',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'ko',
			Sorting: 190,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-07-30T06:47:59.113Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 20,
			DescriptionInfo: {
				Description: 'Vietnamese',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Vietnamese',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'vi',
			Sorting: 200,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-07-30T06:47:59.49Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 21,
			DescriptionInfo: {
				Description: 'Thai',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Thai',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'th',
			Sorting: 210,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-07-30T06:47:59.857Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 22,
			DescriptionInfo: {
				Description: 'Indonesian',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Indonesian',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'id',
			Sorting: 220,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2021-07-30T06:48:00.243Z',
			InsertedBy: 1,
			UpdatedAt: '2022-02-03T10:01:29.707Z',
			UpdatedBy: 1,
			Version: 3,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 27,
			DescriptionInfo: {
				Description: 'Romanian',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Romanian',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'ro',
			Sorting: 230,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2022-09-29T10:32:12.89Z',
			InsertedBy: 1,
			UpdatedAt: '2022-09-29T14:06:13.383Z',
			UpdatedBy: 2736,
			Version: 2,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 28,
			DescriptionInfo: {
				Description: 'Hungarian',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Hungarian',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'hu',
			Sorting: 240,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2023-01-24T12:51:40.557Z',
			InsertedBy: 1,
			UpdatedAt: '2023-01-24T12:52:18.197Z',
			UpdatedBy: 2736,
			Version: 2,
			Codefinance: null,
			FbLanguageFk: null,
		},
		{
			Id: 30,
			DescriptionInfo: {
				Description: 'Flemish',
				DescriptionTr: null,
				DescriptionModified: false,
				Translated: 'Flemish',
				VersionTr: 0,
				Modified: false,
				OtherLanguages: null,
			},
			Culture: 'nl-be',
			Sorting: 260,
			IsDefault: false,
			Islive: true,
			InsertedAt: '2023-04-11T14:19:06.493Z',
			InsertedBy: 1,
			UpdatedAt: '2023-04-20T11:50:20.75Z',
			UpdatedBy: 210,
			Version: 2,
			Codefinance: null,
			FbLanguageFk: null,
		},
	],
	uilanguagessimple: [
		{
			Id: 1,
			Sorting: 10,
			Description: 'English',
			Language: 'en',
			Culture: 'en-gb',
		},
		{
			Id: 3,
			Sorting: 10,
			Description: 'English (US)',
			Language: 'en-us',
			Culture: 'en-us',
		},
		{
			Id: 2,
			Sorting: 20,
			Description: 'German',
			Language: 'de',
			Culture: 'de-de',
		},
		{
			Id: 24,
			Sorting: 20,
			Description: 'German (Swiss)',
			Language: 'de-ch',
			Culture: 'de-ch',
		},
		{
			Id: 4,
			Sorting: 40,
			Description: 'Spanish',
			Language: 'es',
			Culture: 'es-es',
		},
		{
			Id: 5,
			Sorting: 50,
			Description: 'Finnish',
			Language: 'fi',
			Culture: 'fi-fi',
		},
		{
			Id: 6,
			Sorting: 60,
			Description: 'French',
			Language: 'fr',
			Culture: 'fr-fr',
		},
		{
			Id: 25,
			Sorting: 60,
			Description: 'French (Swiss)',
			Language: 'fr-ch',
			Culture: 'fr-ch',
		},
		{
			Id: 7,
			Sorting: 70,
			Description: 'Dutch',
			Language: 'nl',
			Culture: 'nl-nl',
		},
		{
			Id: 8,
			Sorting: 80,
			Description: 'Russian',
			Language: 'ru',
			Culture: 'ru-ru',
		},
		{
			Id: 9,
			Sorting: 90,
			Description: 'Chinese',
			Language: 'zh',
			Culture: 'zh-cn',
		},
		{
			Id: 23,
			Sorting: 90,
			Description: 'Chinese (Traditional)',
			Language: 'zh-hant',
			Culture: 'zh-hant',
		},
		{
			Id: 10,
			Sorting: 100,
			Description: 'Italian',
			Language: 'it',
			Culture: 'it-it',
		},
		{
			Id: 26,
			Sorting: 100,
			Description: 'Italian (Swiss)',
			Language: 'it-ch',
			Culture: 'it-ch',
		},
		{
			Id: 11,
			Sorting: 110,
			Description: 'Czech',
			Language: 'cs',
			Culture: 'cs-cz',
		},
		{
			Id: 12,
			Sorting: 120,
			Description: 'Polish',
			Language: 'pl',
			Culture: 'pl-pl',
		},
		{
			Id: 13,
			Sorting: 130,
			Description: 'Swedish',
			Language: 'sv',
			Culture: 'sv-se',
		},
		{
			Id: 14,
			Sorting: 140,
			Description: 'Norwegian',
			Language: 'nb',
			Culture: 'nb-no',
		},
		{
			Id: 15,
			Sorting: 150,
			Description: 'Lithuanian',
			Language: 'lt',
			Culture: 'lt-lt',
		},
		{
			Id: 16,
			Sorting: 160,
			Description: 'Japanese',
			Language: 'ja',
			Culture: 'ja-jp',
		},
		{
			Id: 17,
			Sorting: 170,
			Description: 'Portuguese',
			Language: 'pt',
			Culture: 'pt-pt',
		},
		{
			Id: 18,
			Sorting: 180,
			Description: 'Danish',
			Language: 'da',
			Culture: 'da-dk',
		},
		{
			Id: 19,
			Sorting: 190,
			Description: 'Korean',
			Language: 'ko',
			Culture: 'ko-kr',
		},
		{
			Id: 20,
			Sorting: 200,
			Description: 'Vietnamese',
			Language: 'vi',
			Culture: 'vi-vn',
		},
		{
			Id: 21,
			Sorting: 210,
			Description: 'Thai',
			Language: 'th',
			Culture: 'th-th',
		},
		{
			Id: 22,
			Sorting: 220,
			Description: 'Indonesian',
			Language: 'id',
			Culture: 'id-id',
		},
		{
			Id: 27,
			Sorting: 230,
			Description: 'Romanian',
			Language: 'ro',
			Culture: 'ro-ro',
		},
		{
			Id: 28,
			Sorting: 240,
			Description: 'Hungarian',
			Language: 'hu',
			Culture: 'hu-hu',
		},
		{
			Id: 30,
			Sorting: 260,
			Description: 'Flemish',
			Language: 'nl-be',
			Culture: 'nl-be',
		},
	],
};

describe('ReportSidebarLanguageItemService', () => {
	let service: PlatformReportLanguageItemService;
	let httpTestingController: HttpTestingController;

	beforeEach(() => {
		TestBed.configureTestingModule({
			imports: [HttpClientModule, HttpClientTestingModule],
		});

		httpTestingController = TestBed.get(HttpTestingController);
		service = TestBed.inject(PlatformReportLanguageItemService);
	});

	afterEach(() => {
		httpTestingController.verify();
	});

	it('Check if getCultureViaId returns the culture', () => {
		const culture = service.getCultureViaId(Language_DATA);
		expect(culture).toBe('nl-nl');
	});

	it('Check if getCultureViaId returns null', () => {
		Language_DATA.activeValue = 1000;
		const culture = service.getCultureViaId(Language_DATA);
		expect(culture).toBeNull();
	});

	it('Check if getCulture function returns the culture', () => {
		const culture = service.getCulture();
		expect(culture).toBeTruthy();
	});

	it('Check getCommonLanguageId function returns the language id', () => {
		let id = service.getCommonLanguageId('nl-nl', Language_DATA.items);
		expect(id).toBe(7);

		id = service.getCommonLanguageId('nl-nlll', Language_DATA.items);
		expect(id).toBe(1);
	});

	it('Check if getLanguageItems fetches the language item', () => {
		service['configurationService']['configLoaded'] = true;
		service['configurationService']['configuration']['serverBaseUrl'] = 'https://apps-int.itwo40.eu/itwo40/daily/services/';

		service.getLanguageItems().subscribe((response) => {
			expect(response).toBeTruthy();
		});

		const req = httpTestingController.expectOne('https://apps-int.itwo40.eu/itwo40/daily/services/cloud/common/getuidatalanguages');
		req.flush(LANG_DATA);
	});
});
