import { IDescriptionInfo, IEntityBase } from '@libs/platform/common';

export interface IWipHeaderEntityGenerated extends IEntityBase {
	Id: number;
	ConfigurationFk: number;
	RubricCategoryFk: number;
	CompanyFk: number;
	CompanyResponsibleFk: number;
	ProjectFk: number;
	LanguageFk: number;
	WipStatusFk: number;
	IsMulticontract: boolean;
	DocumentDate: string;
	Code: string;
	DescriptionInfo: IDescriptionInfo | null;
	CurrencyFk: number;
	ExchangeRate: number;
	ClerkFk: number;
	BusinesspartnerFk: number;
	SubsidiaryFk: number;
	CustomerFk: number;
	PerformedFrom: string;
	PerformedTo: string;
	SearchPattern: string;
	ObjUnitFk: number;
	PaymentTermFiFk: number;
	PaymentTermPaFk: number;
	TaxCodeFk: number;
	VatGroupFk: number;
	BillingSchemaFk: number;
	UserDefined1: string;
	UserDefined2: string;
	UserDefined3: string;
	UserDefined4: string;
	UserDefined5: string;
	UserDefinedDate01: string;
	UserDefinedDate02: string;
	UserDefinedDate03: string;
	UserDefinedDate04: string;
	UserDefinedDate05: string;
	OrdHeaderFk: number;
	PrcStructureFk: number;
	ControllingUnitFk: number;
	AmountNet: number;
	WipVat: number;
	AmountNetOc: number;
	WipVatOc: number;
	Remark: string;
	CommentText: string;
	IsBilled: boolean;
	IsNotAccrual: boolean;
	DateEffective: string;
	ContactFk: number;
	PaymentTermAdFk: number;
	BasSalesTaxMethodFk: number;
	IsCanceled: boolean;
	FactorDJC?: number;
}