/*
 * $Id$
 * Copyright(c) RIB Software GmbH
 */

import { EntityInfo } from '@libs/ui/business-base';
import { PpsCommonEventSequenceLogBehavior } from '../behaviors/pps-common-event-sequence-log-behavior.service';
import { PpsCommonEventSequenceLogDataService } from '../services/pps-common-event-sequence-log-data.service';
import { IPpsLogReportVEntity } from './entities/external_entities/pps-log-report-ventity.interface';

export const PPS_COMMON_EVENT_SEQUENCE_LOG_ENTITY_INFO: EntityInfo = EntityInfo.create<IPpsLogReportVEntity>({
	grid: {
		title: { key: 'productionplanning.common.event.eventSeqLogListTitle' },
		behavior: ctx => ctx.injector.get(PpsCommonEventSequenceLogBehavior),
		containerUuid: '6599ed5c1c3b4cef9404d9c0ae2b7a82',
	},
	dataService: (ctx) => ctx.injector.get(PpsCommonEventSequenceLogDataService),
	dtoSchemeId: { moduleSubModule: 'ProductionPlanning.Common', typeName: 'PpsLogReportVDto' },
	permissionUuid: '2581963f63944bdca59bec07f539cafb',
	layoutConfiguration: {
		groups: [
			{
				gid: 'baseGroup',
				attributes: [
					'Date',
					'PpsItemCode',
					'PpsEntityDescription',
					'RecordCode',
					'RecordDescription',
					'RecordType',
					'ColumnName',
					'OldValueDescription',
					'NewValueDescription',
					'Reason',
					'Remark',
					'Updater',
					'AutoGenerated',
					'RecordId',
				],
			},
		],
		overloads: {},
		labels: {}
	},
});
