/*
 * Copyright(c) RIB Software GmbH
 */

import { IBillHeaderEntity } from '../entities/bill-header-entity.interface';
import { Injectable } from '@angular/core';
import { BasicsSharedCustomizeLookupOverloadProvider } from '@libs/basics/shared';
import { prefixAllTranslationKeys } from '@libs/platform/common';
import { ILayoutConfiguration } from '@libs/ui/common';


@Injectable({
	providedIn: 'root',
})

export class SalesWipRelatedBillLayoutService {
	public generateLayout(): ILayoutConfiguration<IBillHeaderEntity> {
		return {
			groups: [
				{ gid: 'Basic Data', attributes: ['TypeFk', 'RubricCategoryFk', 'ConfigurationFk', 'BillingSchemaFk',
						'ProjectFk', 'LanguageFk', 'BilStatusFk', 'BillDate', 'DatePosted', 'BillNo', 'ConsecutiveBillNo', 'VoucherTypeFk', 'InvoiceTypeFk', 'CurrencyFk', 'ExchangeRate', 'BankTypeFk',
						'BankFk', 'ClerkFk', 'ContractTypeFk', 'AmountNet', 'AmountGross', 'AmountNetOc', 'AmountGrossOc', 'IsCanceled', 'CancellationNo', 'CancellationReason', 'BookingText', 'ObjUnitFk',
						'ControllingUnitFk', 'PrcStructureFk', 'DateEffective', 'BasSalesTaxMethodFk', 'IsNotAccrual', 'BusinesspartnerFk', 'CustomerFk', 'ContactFk', 'BusinesspartnerBilltoFk', 'CustomerBilltoFk',
						'ContactBilltoFk', 'DateDiscount', 'DateNetpayable', 'PaymentTermFk', 'TaxCodeFk', 'VatGroupFk', 'PerformedFrom', 'PerformedTo', 'PrjChangeFk', 'Remark', 'CommentText',
						'UserDefined1', 'UserDefined2', 'UserDefined3', 'UserDefined4', 'UserDefined5', 'UserDefinedDate01', 'UserDefinedDate02', 'UserDefinedDate03', 'UserDefinedDate04', 'UserDefinedDate05'] },
			],
			overloads: {
				TypeFk: BasicsSharedCustomizeLookupOverloadProvider.provideBillTypeLookupOverload(false),
				RubricCategoryFk: BasicsSharedCustomizeLookupOverloadProvider.provideRubricCategoryLookupOverload(false),
				ConfigurationFk: { label: { text: 'ConfigurationFk', key: 'ConfigurationFk' }, visible: true },
				BillingSchemaFk: { label: { text: 'BillingSchemaFk', key: 'BillingSchemaFk' }, visible: true },
				ProjectFk: { label: { text: 'ProjectFk', key: 'ProjectFk' }, visible: true },
				LanguageFk: BasicsSharedCustomizeLookupOverloadProvider.provideLanguageLookupOverload(false),
				BilStatusFk: BasicsSharedCustomizeLookupOverloadProvider.provideBillStatusLookupOverload(false),
				BillDate: { label: { text: 'BillDate', key: 'BillDate' }, visible: true },
				DatePosted: { label: { text: 'PostingDate', key: 'PostingDate' }, visible: true },
				BillNo: { label: { text: 'BillNo', key: 'BillNo' }, visible: true },
				ConsecutiveBillNo: { label: { text: 'ConsecutiveBillNo', key: 'ConsecutiveBillNo' }, visible: true },
				VoucherTypeFk: BasicsSharedCustomizeLookupOverloadProvider.provideVoucherTypeReadonlyLookupOverload(),
				InvoiceTypeFk: BasicsSharedCustomizeLookupOverloadProvider.provideInvoiceTypeReadonlyLookupOverload(),
				CurrencyFk: BasicsSharedCustomizeLookupOverloadProvider.provideCurrencyRateTypeReadonlyLookupOverload(),
				ExchangeRate: { label: { text: 'ExchangeRate', key: 'ExchangeRate' }, visible: true },
				BankTypeFk: BasicsSharedCustomizeLookupOverloadProvider.provideBankTypeReadonlyLookupOverload(),
				BankFk: { label: { text: 'Bank', key: 'Bank' }, visible: true },
				ClerkFk: BasicsSharedCustomizeLookupOverloadProvider.provideClerkRoleLookupOverload(false),
				ContractTypeFk: BasicsSharedCustomizeLookupOverloadProvider.provideProcurementContractTypeLookupOverload(false),
				AmountNet: { label: { text: 'NetAmount', key: 'NetAmount' }, visible: true },
				AmountGross: { label: { text: 'AmountGross', key: 'AmountGross' }, visible: true },
				AmountNetOc: { label: { text: 'AmountNetOc', key: 'AmountNetOc' }, visible: true },
				AmountGrossOc: { label: { text: 'AmountGrossOc', key: 'AmountGrossOc' }, visible: true },
				IsCanceled: { label: { text: 'IsCanceled', key: 'IsCanceled' }, visible: true },
				CancellationNo: { label: { text: 'CancellationNo', key: 'CancellationNo' }, visible: true },
				CancellationReason: { label: { text: 'CancellationReason', key: 'CancellationReason' }, visible: true },
				BookingText: { label: { text: 'BookingText', key: 'BookingText' }, visible: true },
				ObjUnitFk: BasicsSharedCustomizeLookupOverloadProvider.provideObjectUnitTypeReadonlyLookupOverload(),
				ControllingUnitFk: BasicsSharedCustomizeLookupOverloadProvider.provideControllingUnitAssignmentReadonlyLookupOverload(),
				PrcStructureFk: BasicsSharedCustomizeLookupOverloadProvider.provideProcurementContractTypeLookupOverload(false),
				DateEffective: { label: { text: 'DateEffective', key: 'DateEffective' }, visible: true },
				BasSalesTaxMethodFk: BasicsSharedCustomizeLookupOverloadProvider.provideSalesTaxMethodLookupOverload(false),
				IsNotAccrual: { label: { text: 'IsNotAccrual', key: 'IsNotAccrual' }, visible: true },
				BusinesspartnerFk: BasicsSharedCustomizeLookupOverloadProvider.provideRfqBusinessPartnerStatusLookupOverload(false),
				CustomerFk: BasicsSharedCustomizeLookupOverloadProvider.provideCustomerAbcLookupOverload(false),
				ContactFk: BasicsSharedCustomizeLookupOverloadProvider.provideContactRoleLookupOverload(false),
				BusinesspartnerBilltoFk: BasicsSharedCustomizeLookupOverloadProvider.provideRfqBusinessPartnerStatusLookupOverload(false),
				CustomerBilltoFk: BasicsSharedCustomizeLookupOverloadProvider.provideCustomerAbcLookupOverload(false),
				ContactBilltoFk: BasicsSharedCustomizeLookupOverloadProvider.provideContactRoleLookupOverload(false),
				DateDiscount: { label: { text: 'DateDiscount', key: 'DateDiscount' }, visible: true },
				DateNetpayable: { label: { text: 'NetPayable', key: 'NetPayable' }, visible: true },
				PaymentTermFk: BasicsSharedCustomizeLookupOverloadProvider.providePaymentMethodLookupOverload(false),
				TaxCodeFk: BasicsSharedCustomizeLookupOverloadProvider.provideSalesTaxMethodLookupOverload(false),
				VatGroupFk: BasicsSharedCustomizeLookupOverloadProvider.provideVATGroupLookupOverload(false),
				PerformedFrom: { label: { text: 'PerformedFrom', key: 'PerformedFrom' }, visible: true },
				PerformedTo: { label: { text: 'PerformedTo', key: 'PerformedTo' }, visible: true },
				PrjChangeFk: BasicsSharedCustomizeLookupOverloadProvider.provideProjectChangeStatusLookupOverload(false),
				Remark: { label: { text: 'Remark', key: 'Remark' }, visible: true },
				CommentText: { label: { text: 'Comment', key: 'Comment' }, visible: true },
				UserDefined1: { label: { text: 'UserDefined1', key: 'UserDefined1' }, visible: true },
				UserDefined2: { label: { text: 'UserDefined2', key: 'UserDefined2' }, visible: true },
				UserDefined3: { label: { text: 'UserDefined3', key: 'UserDefined3' }, visible: true },
				UserDefined4: { label: { text: 'UserDefined4', key: 'UserDefined4' }, visible: true },
				UserDefined5: { label: { text: 'UserDefined5', key: 'UserDefined5' }, visible: true },
				UserDefinedDate01: { label: { text: 'UserDefinedDate01', key: 'UserDefinedDate01' }, visible: true },
				UserDefinedDate02: { label: { text: 'UserDefinedDate02', key: 'UserDefinedDate02' }, visible: true },
				UserDefinedDate03: { label: { text: 'UserDefinedDate03', key: 'UserDefinedDate03' }, visible: true },
				UserDefinedDate04: { label: { text: 'UserDefinedDate04', key: 'UserDefinedDate04' }, visible: true },
				UserDefinedDate05: { label: { text: 'UserDefinedDate05', key: 'UserDefinedDate05' }, visible: true },
			},
			labels: {
				...prefixAllTranslationKeys('sales.contract.', {
					TypeFk: {key: 'entityTypeFk'},
					RubricCategoryFk: {key: 'entityRubricCategoryFk'},
					ProjectFk: {key: 'entityProjectFk'},
					LanguageFk: {key: 'entityLanguageFk'},
					BilStatusFk: {key: 'entityBilStatusFk'},
					BillDate: {key: 'entityBillDate'},
					DatePosted: {key: 'entityDatePosted'},
					BillNo: {key: 'entityBillNo'},
					ConsecutiveBillNo: {key: 'entityConsecutiveBillNo'},
					VoucherTypeFk: {key: 'entityVoucherTypeFk'},
					InvoiceTypeFk: {key: 'entityInvoiceTypeFk'},
					CurrencyFk: {key: 'entityCurrencyFk'},
					ExchangeRate: {key: 'entityExchangeRate'},
					BankTypeFk: {key: 'entityBankTypeFk'},
					BankFk: {key: 'entityBankFk'},
					ClerkFk: {key: 'entityClerkFk'},
					ContractTypeFk: {key: 'entityContractTypeFk'},
					AmountNet: {key: 'entityAmountNet'},
					AmountGross: {key: 'entityAmountGross'},
					AmountNetOc: {key: 'entityAmountNetOc'},
					AmountGrossOc: {key: 'entityAmountGrossOc'},
					IsCanceled: {key: 'entityIsCanceled'},
					CancellationNo: {key: 'entityCancellationNo'},
					CancellationReason: {key: 'entityCancellationReason'},
					BookingText: {key: 'entityBookingText'},
					ObjUnitFk: {key: 'entityObjUnitFk'},
					ControllingUnitFk: {key: 'entityControllingUnitFk'},
					PrcStructureFk: {key: 'entityPrcStructureFk'},
					DateEffective: {key: 'entityDateEffective'},
					BasSalesTaxMethodFk: {key: 'entityBasSalesTaxMethodFk'},
					IsNotAccrual: {key: 'entityIsNotAccrual'},
					BusinesspartnerFk: {key: 'entityBusinesspartnerFk'},
					CustomerFk: {key: 'entityCustomerFk'},
					ContactFk: {key: 'entityContactFk'},
					BusinesspartnerBilltoFk: {key: 'entityBusinesspartnerBilltoFk'},
					CustomerBilltoFk: {key: 'entityCustomerBilltoFk'},
					ContactBilltoFk: {key: 'entityContactBilltoFk'},
					DateDiscount: {key: 'entityDateDiscount'},
					DateNetpayable: {key: 'entityDateNetpayable'},
					PaymentTermFk: {key: 'entityPaymentTermFk'},
					TaxCodeFk: {key: 'entityTaxCodeFk'},
					VatGroupFk: {key: 'entityVatGroupFk'},
					PerformedFrom: {key: 'entityPerformedFrom'},
					PerformedTo: {key: 'entityPerformedTo'},
					PrjChangeFk: {key: 'entityPrjChangeFk'},
					Remark: {key: 'entityRemark'},
					CommentText: {key: 'entityCommentText'},
					UserDefined1: {key: 'entityUserDefined1'},
					UserDefined2: {key: 'entityUserDefined2'},
					UserDefined3: {key: 'entityUserDefined3'},
					UserDefined4: {key: 'entityUserDefined4'},
					UserDefined5: {key: 'entityUserDefined5'},
					UserDefinedDate01: {key: 'entityUserDefinedDate01'},
					UserDefinedDate02: {key: 'entityUserDefinedDate02'},
					UserDefinedDate03: {key: 'entityUserDefinedDate03'},
					UserDefinedDate04: {key: 'entityUserDefinedDate04'},
					UserDefinedDate05: {key: 'entityUserDefinedDate05'}
				}),
			},
		};
	}
}