/*
 * Copyright(c) RIB Software GmbH
 */
import { BasicsSharedImportEditorType, BasicsSharedImportField } from '@libs/basics/shared';
import { FieldType } from '@libs/ui/common';

export const IMPORT_MAPPING_FIELDS: BasicsSharedImportField[] = [
	{
		PropertyName: 'MaterialCode',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.none,
		DisplayName: 'basics.material.import.materialCode',
	},
	{
		PropertyName: 'MatchCode',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.matchCode',
	},
	{
		PropertyName: 'Description1',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'cloud.common.entityDescription',
	},
	{
		PropertyName: 'Description2',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.furtherDescription',
	},
	{
		PropertyName: 'Specification',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.specification',
	},
	{
		PropertyName: 'ABCGroup',
		EntityName: 'MaterialABC',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.material.materialabc',
		DisplayMember: 'Description',
		DisplayName: 'basics.material.record.aBCGroup',
	},
	{
		PropertyName: 'Currency',
		EntityName: 'BasCurrency',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.currency',
		DisplayMember: 'Currency',
		DisplayName: 'cloud.common.entityCurrency',
	},
	{
		PropertyName: 'Uom',
		EntityName: 'Uom',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.customlookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.uom',
		DisplayMember: 'UOM',
		DisplayName: 'cloud.common.entityUoM',
		//EditorDirective: 'basics-lookupdata-uom-lookup',
		//FormatterOptions: {
		//	lookupType: 'uom',
		//	valueMember: 'Id',
		//	displayMember: 'Unit',
		//},
	},
	{
		PropertyName: 'IsLive',
		EntityName: 'Material',
		DomainName: 'boolean',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.active',
	},
	{
		PropertyName: 'IsProduct',
		EntityName: 'Material',
		DomainName: 'boolean',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.isProduct',
	},
	{
		PropertyName: 'CostType',
		EntityName: 'EstCostType',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		LookupQualifier: 'basics.customize.estcosttype',
		DisplayMember: 'Description',
		DisplayName: 'basics.material.record.estCostTypeFk',
	},
	{
		PropertyName: 'RetailPrice',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.retailPrice',
	},
	{
		PropertyName: 'CostPriceGross',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.costPriceGross',
	},
	{
		PropertyName: 'ListPrice',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.listPrice',
	},
	{
		PropertyName: 'Discount',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.discount',
	},
	{
		PropertyName: 'Charges',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.charges',
	},
	{
		PropertyName: 'PriceCondition',
		EntityName: 'PriceCondition',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'prc.pricecondition',
		DisplayMember: 'description',
		DisplayName: 'cloud.common.entityPriceCondition',
	},
	{
		PropertyName: 'PriceConditionType',
		EntityName: 'MaterialPriceCondition',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'prc.priceconditiontype',
		DisplayMember: 'code',
		DisplayName: 'basics.material.import.priceConditionType',
	},
	{
		PropertyName: 'PriceConditionValue',
		EntityName: 'MaterialPriceCondition',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.priceConditionValue',
	},
	{
		PropertyName: 'EstimatePrice',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.estimatePrice',
	},
	{
		PropertyName: 'DayworkRate',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.DayworkRate',
	},
	{
		PropertyName: 'PriceUnit',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'cloud.common.entityPriceUnit',
	},
	{
		PropertyName: 'LeadTime',
		EntityName: 'Material',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.materialSearchLookup.htmlTranslate.leadTimes',
	},
	{
		PropertyName: 'MinQuantity',
		EntityName: 'Material',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.minQuantity',
	},
	{
		PropertyName: 'PriceUnitUom',
		EntityName: 'Uom',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.customlookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.uom',
		DisplayMember: 'UOM',
		DisplayName: 'cloud.common.entityPriceUnitUoM',
		//EditorDirective: 'basics-lookupdata-uom-lookup',
		//FormatterOptions: {
		//	lookupType: 'uom',
		//	valueMember: 'Id',
		//	displayMember: 'Unit',
		//},
	},
	{
		PropertyName: 'Factor',
		EntityName: 'Material',
		DomainName: 'factor',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'cloud.common.entityFactor',
	},
	{
		PropertyName: 'SellUnit',
		EntityName: 'Material',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.sellUnit',
	},
	{
		PropertyName: 'MaterialDiscountGroup_Code',
		ValueName: 'MaterialDiscountGroup_Id',
		EntityName: 'MaterialDiscountGroup',
		DomainName: 'lookup',
		DisplayName: 'basics.material.record.discountGroup',
		Editor: BasicsSharedImportEditorType.idLookup,
		//EditorDirective: 'basics-material-material-discount-group-lookup',
		//FormatterOptions: {
		//	lookupType: 'materialdiscountgroup',
		//	displayMember: 'Code',
		//},
	},
	{
		PropertyName: 'WeightType',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.weightType',
	},
	{
		PropertyName: 'WeightNumber',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.weightNumber',
	},
	{
		PropertyName: 'Weight',
		EntityName: 'Material',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.weight',
	},
	{
		PropertyName: 'ExternalCode',
		EntityName: 'Material',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.externalCode',
	},
	{
		PropertyName: 'TaxCode',
		EntityName: 'Tax',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'masterdata.context.taxcode',
		DisplayMember: 'Code',
		DisplayName: 'cloud.common.entityTaxCode',
	},
	{
		PropertyName: 'NeutralMaterial_Code',
		ValueName: 'NeutralMaterial_Id',
		EntityName: 'NeutralMaterial',
		DomainName: 'lookup',
		Editor: BasicsSharedImportEditorType.idLookup,
		DisplayName: 'basics.material.record.neutralMaterial',
		//EditorDirective: 'basics-material-common-material-lookup',
		//FormatterOptions: {
		//	lookupType: 'materialrecord',
		//	displayMember: 'Code',
		//},
	},
	{
		PropertyName: 'BpdAgreement_Description',
		ValueName: 'BpdAgreement_Id',
		EntityName: 'BpdAgreement',
		DomainName: 'lookup',
		DisplayName: 'basics.material.record.partnerAgreement',
		Editor: BasicsSharedImportEditorType.idLookup,
		//EditorDirective: 'business-partner-main-agreement-lookup',
		//FormatterOptions: {
		//	lookupType: 'Agreement',
		//	displayMember: 'Description',
		//},
	},
	{
		PropertyName: 'Image',
		EntityName: 'Blobs',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.none,
		readonly: true,
		DisplayName: 'basics.material.import.image',
		SelectLoad: true,
	},
	{
		PropertyName: 'BlobSpecification',
		EntityName: 'Blobs',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.none,
		DisplayName: 'basics.material.import.blobSpecification',
	},
	{
		PropertyName: '3DModelFile',
		EntityName: 'ModelView',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.none,
		readonly: true,
		DisplayName: 'basics.material.import.3DView',
		SelectLoad: true,
	},
	{
		PropertyName: 'LeadTimeExtra',
		EntityName: 'Material',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'cloud.common.entityLeadTimeExtra',
	},
	{
		PropertyName: 'UserDefined1',
		EntityName: 'Userdefined1',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefined1',
	},
	{
		PropertyName: 'UserDefined2',
		EntityName: 'Userdefined2',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefined2',
	},
	{
		PropertyName: 'UserDefined3',
		EntityName: 'Userdefined3',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefined3',
	},
	{
		PropertyName: 'UserDefined4',
		EntityName: 'Userdefined4',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefined4',
	},
	{
		PropertyName: 'UserDefined5',
		EntityName: 'Userdefined5',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefined5',
	},
	{
		PropertyName: 'MdcBrand',
		EntityName: 'MdcBrand',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.material.brand',
		DisplayMember: 'Description',
		DisplayName: 'basics.material.import.mdcBrand',
	},
	{
		PropertyName: 'ModelName',
		EntityName: 'ModelName',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.modelName',
	},
	{
		PropertyName: 'UserDefinedText1',
		EntityName: 'UserDefinedText1',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedText1',
	},
	{
		PropertyName: 'UserDefinedText2',
		EntityName: 'UserDefinedText2',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedText2',
	},
	{
		PropertyName: 'UserDefinedText3',
		EntityName: 'UserDefinedText3',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedText3',
	},
	{
		PropertyName: 'UserDefinedText4',
		EntityName: 'UserDefinedText4',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedText4',
	},
	{
		PropertyName: 'UserDefinedText5',
		EntityName: 'UserDefinedText5',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedText5',
	},
	{
		PropertyName: 'UserDefinedDate1',
		EntityName: 'UserDefinedDate1',
		DomainName: 'date',
		IsDefaultNullForDomain: true,
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedDate1',
	},
	{
		PropertyName: 'UserDefinedDate2',
		EntityName: 'UserDefinedDate2',
		DomainName: 'date',
		IsDefaultNullForDomain: true,
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedDate2',
	},
	{
		PropertyName: 'UserDefinedDate3',
		EntityName: 'UserDefinedDate3',
		DomainName: 'date',
		IsDefaultNullForDomain: true,
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedDate3',
	},
	{
		PropertyName: 'UserDefinedDate4',
		EntityName: 'UserDefinedDate4',
		DomainName: 'date',
		IsDefaultNullForDomain: true,
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedDate4',
	},
	{
		PropertyName: 'UserDefinedDate5',
		EntityName: 'UserDefinedDate5',
		DomainName: 'date',
		IsDefaultNullForDomain: true,
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedDate5',
	},
	{
		PropertyName: 'UserDefinedNumber1',
		EntityName: 'UserDefinedNumber1',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedNumber1',
	},
	{
		PropertyName: 'UserDefinedNumber2',
		EntityName: 'UserDefinedNumber2',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedNumber2',
	},
	{
		PropertyName: 'UserDefinedNumber3',
		EntityName: 'UserDefinedNumber3',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedNumber3',
	},
	{
		PropertyName: 'UserDefinedNumber4',
		EntityName: 'UserDefinedNumber4',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedNumber4',
	},
	{
		PropertyName: 'UserDefinedNumber5',
		EntityName: 'UserDefinedNumber5',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.userdefinedNumber5',
	},
	{
		PropertyName: 'MaterialTempCatalog_Code',
		ValueName: 'MaterialTempCatalog_Id',
		EntityName: ' MaterialTempCatalog',
		DomainName: 'lookup',
		Editor: BasicsSharedImportEditorType.idLookup,
		DisplayName: 'basics.material.record.materialTemplateCatalog',
		//EditorDirective: 'basics-material-material-catalog-dialog-lookup',
		//NotUseDefaultValue: true,
		//FormatterOptions: {
		//	lookupType: 'MaterialCatalog',
		//	displayMember: 'Code',
		//},
	},
	{
		PropertyName: 'MaterialTemp_Code',
		ValueName: 'MaterialTemp_Id',
		EntityName: ' MaterialTemp',
		DomainName: 'lookup',
		Editor: BasicsSharedImportEditorType.idLookup,
		DisplayName: 'basics.material.record.materialTemplate',
		//EditorDirective: 'basics-material-common-material-lookup',
		//NotUseDefaultValue: true,
		//FormatterOptions: {
		//	lookupType: 'MaterialRecord',
		//	displayMember: 'Code',
		//},
	},
	{
		PropertyName: 'MaterialTempType',
		EntityName: 'MaterialTempType',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		LookupQualifier: 'basics.customize.materialtemplatetype',
		DisplayMember: 'Description',
		DisplayName: 'basics.material.record.materialTemplateType',
	},
	{
		PropertyName: 'DangerClass',
		EntityName: 'DangerClass',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.customize.dangerclass',
		DisplayMember: 'Code',
		DisplayName: 'cloud.common.entityDangerClass',
	},
	{
		PropertyName: 'PackageType',
		EntityName: 'PackageType',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.customize.packagingtypes',
		DisplayMember: 'Description',
		DisplayName: 'cloud.common.entityPackagingType',
	},
	{
		PropertyName: 'UomVolume',
		EntityName: 'Uom',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.customlookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.uom',
		DisplayMember: 'UOM',
		DisplayName: 'cloud.common.entityUomVolume',
		//EditorDirective: 'basics-lookupdata-uom-lookup',
		//FormatterOptions: {
		//	lookupType: 'uom',
		//	valueMember: 'Id',
		//	displayMember: 'Unit',
		//},
	},
	{
		PropertyName: 'Volume',
		EntityName: 'Volume',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'cloud.common.entityVolume',
	},
	{
		PropertyName: 'UomWeight',
		EntityName: 'UomWeight',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.customlookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.uom',
		DisplayMember: 'UOM',
		DisplayName: 'basics.material.record.uomWeight',
		//EditorDirective: 'basics-lookupdata-uom-lookup',
		//FormatterOptions: {
		//	lookupType: 'uom',
		//	valueMember: 'Id',
		//	displayMember: 'Unit',
		//},
	},
	{
		PropertyName: 'MaterialType',
		EntityName: 'MaterialType',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		LookupQualifier: 'basics.customize.materialtype',
		DisplayMember: 'Description',
		DisplayName: 'basics.material.record.materialType',
	},
	{
		PropertyName: 'DocumentBlobSpecification',
		EntityName: 'Blobs',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.none,
		DisplayName: 'basics.material.import.documentBlobSpecification',
	},
	{
		PropertyName: 'Co2Source',
		EntityName: 'Co2Source',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.entityCo2Source',
	},
	{
		PropertyName: 'Co2Project',
		EntityName: 'Co2Project',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.entityCo2Project',
	},
	{
		PropertyName: 'BasCo2SourceName',
		EntityName: 'BasCo2SourceName',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.customlookup,
		DisplayMember: 'BasCo2SourceName',
		DisplayName: 'basics.material.record.entityBasCo2SourceFk',
		//EditorDirective: 'basics-lookupdata-source-name-lookup',
		//FormatterOptions: {
		//	lookupType: 'co2sourcename',
		//	valueMember: 'Id',
		//	displayMember: 'DescriptionInfo.Translated',
		//	version: 3,
		//},
	},
];

export const IMPORT_MAPPING_PRICE_LIST_FIELDS = [
	{
		PropertyName: 'PriceVersion',
		EntityName: 'MatPriceVer',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.none,
		DisplayName: 'basics.materialcatalog.priceVersions',
		ColumnNameReadOnly: true,
	},
	{
		PropertyName: 'MaterialCode',
		EntityName: 'Material',
		DomainName: 'code',
		Editor: BasicsSharedImportEditorType.none,
		DisplayName: 'basics.material.import.materialCode',
		ColumnNameReadOnly: true,
	},
	{
		PropertyName: 'Currency',
		EntityName: 'BasCurrency',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'basics.currency',
		DisplayMember: 'Currency',
		DisplayName: 'cloud.common.entityCurrency',
	},
	{
		PropertyName: 'RetailPrice',
		EntityName: 'MatPriceList',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.retailPrice',
	},
	{
		PropertyName: 'ListPrice',
		EntityName: 'MatPriceList',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.listPrice',
	},
	{
		PropertyName: 'Discount',
		EntityName: 'MatPriceList',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.discount',
	},
	{
		PropertyName: 'Charges',
		EntityName: 'MatPriceList',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.charges',
	},
	{
		PropertyName: 'LeadTime',
		EntityName: 'MatPriceList',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.materialSearchLookup.htmlTranslate.leadTimes',
	},
	{
		PropertyName: 'MinQuantity',
		EntityName: 'MatPriceList',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.minQuantity',
	},
	{
		PropertyName: 'SellUnit',
		EntityName: 'MatPriceList',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.sellUnit',
	},
	{
		PropertyName: 'TaxCode',
		EntityName: 'Tax',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'masterdata.context.taxcode',
		DisplayMember: 'Code',
		DisplayName: 'cloud.common.entityTaxCode',
	},
	{
		PropertyName: 'PriceCondition',
		EntityName: 'PriceCondition',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'prc.pricecondition',
		DisplayMember: 'description',
		DisplayName: 'cloud.common.entityPriceCondition',
	},
	{
		PropertyName: 'PriceConditionType',
		EntityName: 'MaterialPriceCondition',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.simplelookup,
		NotUseDefaultValue: true,
		LookupQualifier: 'prc.priceconditiontype',
		DisplayMember: 'code',
		DisplayName: 'basics.material.import.priceConditionType',
	},
	{
		PropertyName: 'PriceConditionValue',
		EntityName: 'MaterialPriceCondition',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.import.priceConditionValue',
	},
	{
		PropertyName: 'EstimatePrice',
		EntityName: 'MatPriceList',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.estimatePrice',
	},
	{
		PropertyName: 'DayworkRate',
		EntityName: 'MatPriceList',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.dayworkRate',
	},
	{
		PropertyName: 'Co2Source',
		EntityName: 'Co2Source',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.entityCo2Source',
	},
	{
		PropertyName: 'Co2Project',
		EntityName: 'Co2Project',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		DisplayName: 'basics.material.record.entityCo2Project',
	},
	{
		PropertyName: 'BasCo2SourceName',
		ValueName: 'BasCo2Source_Id',
		EntityName: 'BasCo2SourceFk',
		DomainName: 'lookup',
		Editor: BasicsSharedImportEditorType.idLookup,
		DisplayName: 'basics.material.record.entityBasCo2SourceFk',
		DisplayMember: 'DescriptionInfo.Translate',
		type: FieldType.Integer,
		//EditorDirective: 'basics-lookupdata-source-name-lookup',
		//FormatterOptions: {
		//	lookupType: 'co2sourcename',
		//	displayMember: 'DescriptionInfo.Translated',
		//},
	},
];

export const VARIANT_FIELDS = [
	{ PropertyName: 'IsSelected', Description: 'Is Selected', DomainName: 'boolean' },
	{ PropertyName: 'MatScope', Description: 'Code', Editor: BasicsSharedImportEditorType.none },
	{ PropertyName: 'Description', Description: 'Description' },
	{ PropertyName: 'BusinessPartner', Description: 'Business Partner', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, LookupQualifier: 'businesspartner.lookup.businesspartner', DisplayMember: 'BP_NAME1' },
	{ PropertyName: 'Subsidiary', Description: 'Subsidiary', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, LookupQualifier: 'businesspartner.subsidiary', DisplayMember: 'Description' },
	{ PropertyName: 'Supplier', Description: 'Supplier', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, LookupQualifier: 'businesspartner.supplier', DisplayMember: 'Code', AlternativeMember: 'description' },
	{
		PropertyName: 'BusinessPartnerProd',
		Description: 'Business Partner Producer',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		LookupQualifier: 'businesspartner.lookup.businesspartner',
		DisplayMember: 'BP_NAME1',
	},
	{ PropertyName: 'SubsidiaryProd', Description: 'Subsidiary Producer', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, LookupQualifier: 'businesspartner.subsidiary', DisplayMember: 'Description' },
	{ PropertyName: 'SupplierProd', Description: 'Supplier Producer', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, LookupQualifier: 'businesspartner.supplier', DisplayMember: 'Code' },
	{ PropertyName: 'Comment', Description: 'Comment' },
	{ PropertyName: 'Remark', Description: 'Remark' },
	{ PropertyName: 'UserDefined1', Description: 'User Defined 1' },
	{ PropertyName: 'UserDefined2', Description: 'User Defined 2' },
	{ PropertyName: 'UserDefined3', Description: 'User Defined 3' },
	{ PropertyName: 'UserDefined4', Description: 'User Defined 4' },
	{ PropertyName: 'UserDefined5', Description: 'User Defined 5' },
	{ PropertyName: 'Active', Description: 'Is Live', DomainName: 'boolean' },
];

export const SUPPLY_FIELDS = [
	{ PropertyName: 'ScopeType', Description: 'Scope Type', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simplelookup, LookupQualifier: 'basics.material.scopeofsupplytype', DisplayMember: 'Description' },
	{ PropertyName: 'ItemNo', Description: 'Item No', Editor: BasicsSharedImportEditorType.none },
	{ PropertyName: 'Structure', Description: 'Structure', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, LookupQualifier: 'prc.structure.withcontext', DisplayMember: 'Code' },
	{ PropertyName: 'Description1', Description: 'Description' },
	{ PropertyName: 'Description2', Description: 'Further Description' },
	{ PropertyName: 'Specification', Description: 'Specification' },
	{ PropertyName: 'Quantity', Description: 'Quantity', DomainName: 'quantity' },
	{ PropertyName: 'Uom', Description: 'Uom', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simplelookup, LookupQualifier: 'basics.uom', DisplayMember: 'UOM' },
	{ PropertyName: 'Price', Description: 'Price', DomainName: 'money' },
	{ PropertyName: 'PriceCondition', Description: 'Price Condition', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simplelookup, NotUseDefaultValue: true, LookupQualifier: 'prc.pricecondition' },
	{ PropertyName: 'PriceUnit', Description: 'Price Unit', DomainName: 'quantity' },
	{ PropertyName: 'UomPriceUnit', Description: 'Price Unit Uom', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simplelookup, LookupQualifier: 'basics.uom', DisplayMember: 'UOM' },
	{ PropertyName: 'FactorPriceUnit', Description: 'Factor', DomainName: 'quantity' },
	{ PropertyName: 'DateRequired', Description: 'Date Required', DomainName: 'date' },
	{ PropertyName: 'PaymentTermFi', Description: 'Payment Term FI', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, NotUseDefaultValue: true, LookupQualifier: 'basics.lookup.paymentterm', DisplayMember: 'Code' },
	{ PropertyName: 'PaymentTermPa', Description: 'Payment Term PA', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, NotUseDefaultValue: true, LookupQualifier: 'basics.lookup.paymentterm', DisplayMember: 'Code' },
	{ PropertyName: 'Incoterm', Description: 'Incoterm', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, NotUseDefaultValue: true, LookupQualifier: 'basics.customize.incoterm', DisplayMember: 'Description' },
	{ PropertyName: 'Address', Description: 'Address' },
	{ PropertyName: 'SupplierReference', Description: 'Supplier Reference' },
	{ PropertyName: 'Trademark', Description: 'Trademark' },
	{ PropertyName: 'Comment', Description: 'Comment' },
	{ PropertyName: 'Remark', Description: 'Remark' },
	{ PropertyName: 'BatchNo', Description: 'Batch No' },
	{ PropertyName: 'UserDefined1', Description: 'User Defined 1' },
	{ PropertyName: 'UserDefined2', Description: 'User Defined 2' },
	{ PropertyName: 'UserDefined3', Description: 'User Defined 3' },
	{ PropertyName: 'UserDefined4', Description: 'User Defined 4' },
	{ PropertyName: 'UserDefined5', Description: 'User Defined 5' },
	{ PropertyName: 'MaterialFk', Description: 'Material Code', DomainName: 'integer', Editor: BasicsSharedImportEditorType.simpledescriptionlookup, LookupQualifier: 'basics.material.neutralmaterial', DisplayMember: 'Code' },
];
