/*
 * Copyright(c) RIB Software GmbH
 */

export enum WorkflowActionDetailEnumStandard {
	actionType = 'actionType',
	action = 'action',
	code = 'code',
	description = 'description',
	comment = 'comment',
	executeCondition = 'executeCondition',
	result = 'result',
	userDefined1 = 'userDefined1',
	userDefined2 = 'userDefined2',
	userDefined3 = 'userDefined3',
	userDefined4 = 'userDefined4',
	userDefined5 = 'userDefined5',
	userDefinedMoney1 = 'userDefinedMoney1',
	userDefinedMoney2 = 'userDefinedMoney2',
	userDefinedMoney3 = 'userDefinedMoney3',
	userDefinedMoney4 = 'userDefinedMoney4',
	userDefinedMoney5 = 'userDefinedMoney5',
	userDefinedDate1 = 'userDefinedDate1',
	userDefinedDate2 = 'userDefinedDate2',
	userDefinedDate3 = 'userDefinedDate3',
	userDefinedDate4 = 'userDefinedDate4',
	userDefinedDate5 = 'userDefinedDate5',
	lifeTime = 'lifeTime',
}
export enum WorkflowActionDetailEnumStartEnd {
	code = 'Code',
	description = 'Description',
	comment = 'Comment',
	result = 'Result',
}

export enum WorkflowActionDetailEnumDecision {
	actionType= 'actionType',
	action = 'action',
	code = 'code',
	description = 'description',
	comment = 'comment',
	executeCondition = 'executeCondition',
	result = 'result',
	userDefined1 = 'userDefined1',
	userDefined2 = 'userDefined2',
	userDefined3 = 'userDefined3',
	userDefined4 = 'userDefined4',
	userDefined5 = 'userDefined5',
	userDefinedMoney1 = 'userDefinedMoney1',
	userDefinedMoney2 = 'userDefinedMoney2',
	userDefinedMoney3 = 'userDefinedMoney3',
	userDefinedMoney4 = 'userDefinedMoney4',
	userDefinedMoney5 = 'userDefinedMoney5',
	userDefinedDate1 = 'userDefinedDate1',
	userDefinedDate2 = 'userDefinedDate2',
	userDefinedDate3 = 'userDefinedDate3',
	userDefinedDate4 = 'userDefinedDate4',
	userDefinedDate5 = 'userDefinedDate5',
	lifeTime = 'lifeTime',
	endTime = 'endTime',
	bpId = 'bpId',
	clerkLookUp = 'clerkLookUp',
	priority = 'priority',
}

export enum WorkflowActionDetailEnumDecisionNode {
	parameter = 'parameter',
	description = 'description',
	comment = 'comment',
	result = 'result',
	userDefined1 = 'userDefined1',
	userDefined2 = 'userDefined2',
	userDefined3 = 'userDefined3',
	userDefined4 = 'userDefined4',
	userDefined5 = 'userDefined5',
	userDefinedMoney1 = 'userDefinedMoney1',
	userDefinedMoney2 = 'userDefinedMoney2',
	userDefinedMoney3 = 'userDefinedMoney3',
	userDefinedMoney4 = 'userDefinedMoney4',
	userDefinedMoney5 = 'userDefinedMoney5',
	userDefinedDate1 = 'userDefinedDate1',
	userDefinedDate2 = 'userDefinedDate2',
	userDefinedDate3 = 'userDefinedDate3',
	userDefinedDate4 = 'userDefinedDate4',
	userDefinedDate5 = 'userDefinedDate5',

}