/*
 * Copyright(c) RIB Software GmbH
 */
import { BasicsSharedImportEditorType, BasicsSharedImportField } from '@libs/basics/shared';
import { FieldType } from '@libs/ui/common';

export const ITEM_IMPORT_MAPPING_FIELDS: BasicsSharedImportField[] = [
	{
		PropertyName: 'ITEMNO',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemItemNoForImport',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'ITEMNO',
		type: FieldType.Integer,
		ribFormatMappingName: 'Item Number',
		only4RibFormat: false,
		sortable: false
	}, {
		PropertyName: 'PRC_STRUCTURE_FK',
		EntityName: 'PrcStructure',
		DisplayName: 'cloud.common.entityStructureCode',
		DomainName: 'integer',
		Editor: BasicsSharedImportEditorType.simplelookup,
		DisplayMember: 'Code',
		model: 'PRC_STRUCTURE_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'MATERIAL_CATALOG_CODE',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemMaterialCatalogCode',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'MATERIAL_CATALOG_CODE',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'MDC_MATERIAL_FK',
		EntityName: 'Material',
		DisplayName: 'procurement.common.prcItemMaterialNoForImport',
		DomainName: 'integer',
		LookupQualifier: 'materialrecord',
		Editor: BasicsSharedImportEditorType.customlookup,
		DisplayMember: 'Code',
		model: 'MDC_MATERIAL_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'DESCRIPTION1',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemDescription1',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'DESCRIPTION1',
		type: FieldType.Description,
		ribFormatMappingName: 'Description 1',
		sortable: false
	}, {
		PropertyName: 'DESCRIPTION2',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemFurtherDescription',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'DESCRIPTION2',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'SPECIFICATION',
		EntityName: 'PrcItem',
		DisplayName: 'cloud.common.EntitySpec',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'SPECIFICATION',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'QUANTITY',
		EntityName: 'PrcItem',
		DisplayName: 'cloud.common.entityQuantity',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'QUANTITY',
		type: FieldType.Quantity,
		ribFormatMappingName: 'Quantity',
		sortable: false
	}, {
		PropertyName: 'BAS_UOM_FK',
		EntityName: 'BasUom',
		DisplayName: 'cloud.common.entityUoM',
		DomainName: 'integer',
		LookupQualifier: 'basics.uom',
		Editor: BasicsSharedImportEditorType.simplelookup,
		DisplayMember: 'UOM',
		model: 'BAS_UOM_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'PRICE_OC',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemPriceCurrency',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'PRICE_OC',
		type: FieldType.Money,
		ribFormatMappingName: 'Price',
		notShowInMappingGrid: false,
		sortable: false
	}, {
		PropertyName: 'CHARGE_OC',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.entityChargeOc',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'CHARGE_OC',
		type: FieldType.Money,
		ribFormatMappingName: 'Charge',
		notShowInMappingGrid: false,
		sortable: false
	}, {
		PropertyName: 'PRICE_OC_GROSS',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.priceOcGross',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'PRICE_OC_GROSS',
		type: FieldType.Money,
		NotUseDefaultValue: true,
		notShowInMappingGrid: true,
		sortable: false
	}, {
		PropertyName: 'PRC_PRICECONDITION_FK',
		EntityName: 'PriceCondition',
		DisplayName: 'cloud.common.entityPriceCondition',
		DomainName: 'integer',
		LookupQualifier: 'prc.pricecondition',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'description',
		model: 'PRC_PRICECONDITION_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'PRICE_UNIT',
		EntityName: 'PrcItem',
		DisplayName: 'cloud.common.entityPriceUnit',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'PRICE_UNIT',
		type: FieldType.Money,
		NotUseDefaultValue: true,
		sortable: false
	}, {
		PropertyName: 'BAS_UOM_PRICE_UNIT_FK',
		EntityName: 'Uom',
		DisplayName: 'cloud.common.entityPriceUnitUoM',
		DomainName: 'integer',
		LookupQualifier: 'basics.uom',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'UOM',
		model: 'BAS_UOM_PRICE_UNIT_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'FACTOR_PRICE_UNIT',
		EntityName: 'PrcItem',
		DisplayName: 'cloud.common.entityFactor',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'FACTOR_PRICE_UNIT',
		type: FieldType.Money,
		NotUseDefaultValue: true,
		sortable: false
	}, {
		PropertyName: 'MDC_CONTROLLINGUNIT_FK',
		EntityName: 'Controllingunit',
		DisplayName: 'cloud.common.entityControllingUnitCode',
		DomainName: 'integer',
		LookupQualifier: 'masterdata.context.controllingunit.withcontext',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'Code',
		AlternativeMember: 'description',
		model: 'MDC_CONTROLLINGUNIT_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'TARGET_PRICE',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemTargetPrice',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'TARGET_PRICE',
		type: FieldType.Money,
		NotUseDefaultValue: true,
		sortable: false
	}, {
		PropertyName: 'TARGET_PRICE_GROSS',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemTargetPrice',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'TARGET_PRICE_GROSS',
		type: FieldType.Money,
		NotUseDefaultValue: true,
		notShowInMappingGrid: true,
		sortable: false
	}, {
		PropertyName: 'DATE_REQUIRED',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.DateRequired',
		DomainName: 'date',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'DATE_REQUIRED',
		type: FieldType.Date,
		NotUseDefaultValue: true,
		sortable: false
	}, {
		PropertyName: 'ONHIRE',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.OnHire',
		DomainName: 'date',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'ONHIRE',
		type: FieldType.Date,
		NotUseDefaultValue: true,
		sortable: false
	}, {
		PropertyName: 'OFFHIRE',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.OffHire',
		DomainName: 'date',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'OFFHIRE',
		type: FieldType.Date,
		NotUseDefaultValue: true,
		sortable: false
	}, {
		PropertyName: 'MDC_TAX_CODE_FK',
		EntityName: 'TaxCode',
		DisplayName: 'cloud.common.entityTaxCode',
		DomainName: 'integer',
		LookupQualifier: 'masterdata.context.taxcode',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'Code',
		NotUseDefaultValue: true,
		AlternativeMember: 'description',
		model: 'MDC_TAX_CODE_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'BAS_PAYMENT_TERM_FI_FK',
		EntityName: 'PaymentTerm',
		DisplayName: 'cloud.common.entityPaymentTermFI',
		DomainName: 'integer',
		LookupQualifier: 'basics.lookup.paymentterm',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'Code',
		NotUseDefaultValue: true,
		AlternativeMember: 'description',
		model: 'BAS_PAYMENT_TERM_FI_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'BAS_PAYMENT_TERM_PA_FK',
		EntityName: 'PaymentTerm',
		DisplayName: 'cloud.common.entityPaymentTermPA',
		DomainName: 'integer',
		LookupQualifier: 'basics.lookup.paymentterm',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'Code',
		NotUseDefaultValue: true,
		AlternativeMember: 'description',
		model: 'BAS_PAYMENT_TERM_PA_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'PRC_INCOTERM_FK',
		EntityName: 'PrcIncoterm',
		DisplayName: 'cloud.common.entityIncoterms',
		DomainName: 'integer',
		LookupQualifier: 'prc.incoterm',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'Description',
		NotUseDefaultValue: true,
		model: 'PRC_INCOTERM_FK',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'SUPPLIERREFERENCE',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemSupplierReference',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'SUPPLIERREFERENCE',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'QUANTITY_ASKEDFOR',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemQuantityAskedfor',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'QUANTITY_ASKEDFOR',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'QUANTITY_DELIVERED',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemQuantityDelivered',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'QUANTITY_DELIVERED',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'QUANTITY_CONFIRM',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.delivery.quantityConfirm',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'QUANTITY_CONFIRM',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'DELIVERDATE_CONFIRM',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.delivery.deliverdateConfirm',
		DomainName: 'date',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'DELIVERDATE_CONFIRM',
		NotUseDefaultValue: true,
		type: FieldType.Date,
		sortable: false
	}, {
		PropertyName: 'SAFETY_LEADTIME',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.safetyLeadTime',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'SAFETY_LEADTIME',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'BUFFER_LEADTIME',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.bufferLeadTime',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'BUFFER_LEADTIME',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'LEADTIME_EXTRA',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.leadTimeExtra',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'LEADTIME_EXTRA',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'USERDEFINED1',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.userDefined1',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'USERDEFINED1',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'USERDEFINED2',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.userDefined2',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'USERDEFINED2',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'USERDEFINED3',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.userDefined3',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'USERDEFINED3',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'USERDEFINED4',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.userDefined4',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'USERDEFINED4',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'USERDEFINED5',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.userDefined5',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'USERDEFINED5',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'IsFreeQuantity',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.isFreeQuantity',
		DomainName: 'Boolean',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'IsFreeQuantity',
		NotUseDefaultValue: true,
		type: FieldType.Boolean,
		sortable: false
	}, {
		PropertyName: 'LEADTIME',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.entityLeadTime',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'LEADTIME',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'MIN_QUANTITY',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.prcItemMinQuantity',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'MIN_QUANTITY',
		NotUseDefaultValue: true,
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'ITEM_TYPE',
		EntityName: 'ItemType',
		DisplayName: 'procurement.common.prcItemType',
		DomainName: 'integer',
		LookupQualifier: 'basics.itemtype',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'description',
		NotUseDefaultValue: true,
		AlternativeMember: 'code',
		model: 'ITEM_TYPE',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'ITEM_TYPE2',
		EntityName: 'ItemType2',
		DisplayName: 'procurement.common.prcItemType2',
		DomainName: 'integer',
		LookupQualifier: 'basics.itemType2',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'description',
		NotUseDefaultValue: true,
		AlternativeMember: 'code',
		model: 'ITEM_TYPE2',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'ITEM_TYPE85',
		EntityName: 'ItemType85',
		DisplayName: 'procurement.common.prcItemType85',
		DomainName: 'integer',
		LookupQualifier: 'basics.itemtype85',
		Editor: BasicsSharedImportEditorType.simpledescriptionlookup,
		DisplayMember: 'description',
		NotUseDefaultValue: true,
		AlternativeMember: 'code',
		model: 'ITEM_TYPE85',
		type: FieldType.Integer,
		sortable: false
	}, {
		PropertyName: 'COMMENT_CLIENT',
		EntityName: 'CommentClient',
		DisplayName: 'procurement.common.commentClient',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'COMMENT_CLIENT',
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'COMMENT_CONTRACTOR',
		EntityName: 'CommentContractor',
		DisplayName: 'procurement.common.commentContractor',
		DomainName: 'description',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'COMMENT_CONTRACTOR',
		notShowInMappingGrid: false,
		type: FieldType.Description,
		sortable: false
	}, {
		PropertyName: 'CO2_PROJECT',
		EntityName: 'Co2Project',
		DisplayName: 'procurement.common.entityCo2Project',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'CO2_PROJECT',
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'CO2_PROJECT_TOTAL',
		EntityName: 'Co2Project',
		DisplayName: 'procurement.common.entityCo2ProjectTotal',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'CO2_PROJECT_TOTAL',
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'CO2_SOURCE',
		EntityName: 'Co2Source',
		DisplayName: 'procurement.common.entityCo2Source',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'CO2_SOURCE',
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'CO2_SOURCE_TOTAL',
		EntityName: 'Co2SourceTotal',
		DisplayName: 'procurement.common.entityCo2SourceTotal',
		DomainName: 'quantity',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'CO2_SOURCE_TOTAL',
		type: FieldType.Quantity,
		sortable: false
	}, {
		PropertyName: 'DISCOUNT_ABSOLUTE_OC',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.DiscountAbsoluteOc',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'DISCOUNT_ABSOLUTE_OC',
		NotUseDefaultValue: true,
		type: FieldType.Money,
		sortable: false
	}, {
		PropertyName: 'DISCOUNT_ABSOLUTE_GROSS_OC',
		EntityName: 'PrcItem',
		DisplayName: 'procurement.common.DiscountAbsoluteGrossOc',
		DomainName: 'money',
		Editor: BasicsSharedImportEditorType.domain,
		model: 'DISCOUNT_ABSOLUTE_GROSS_OC',
		NotUseDefaultValue: true,
		type: FieldType.Money,
		sortable: false
	}
];

