/*
 * Copyright(c) RIB Software GmbH
 */

import { CompareFields } from '../compare-fields';

export const ItemCompareFields = {
	price: CompareFields.price,
	priceOc: CompareFields.priceOc,
	priceExtra: CompareFields.priceExtra,
	priceExtraOc: CompareFields.priceExtraOc,
	priceUnit: CompareFields.priceUnit,
	totalPrice: CompareFields.totalPrice,
	totalPriceOc: CompareFields.totalPriceOc,
	total: CompareFields.total,
	rank: CompareFields.rank,
	percentage: CompareFields.percentage,
	prcItemEvaluationFk: CompareFields.prcItemEvaluationFk,
	prcPriceConditionFk: CompareFields.prcPriceConditionFk,
	userDefined1: CompareFields.quoteUserDefined1,
	userDefined2: CompareFields.quoteUserDefined2,
	userDefined3: CompareFields.quoteUserDefined3,
	userDefined4: CompareFields.quoteUserDefined4,
	userDefined5: CompareFields.quoteUserDefined5,
	leadTime: CompareFields.leadTime,
	leadTimeExtra: CompareFields.leadTimeExtra,
	quantity: CompareFields.quantity,
	alternativeBid: CompareFields.alternativeBid,
	totalOC: CompareFields.totalOC,
	priceGross: CompareFields.priceGross,
	priceOCGross: CompareFields.priceOCGross,
	totalPriceGross: CompareFields.totalPriceGross,
	totalPriceOCGross: CompareFields.totalPriceOCGross,
	totalGross: CompareFields.totalGross,
	totalOCGross: CompareFields.totalOCGross,
	discount: CompareFields.discount,
	discountAbsolute: CompareFields.discountAbsolute,
	discountAbsoluteOc: CompareFields.discountAbsoluteOc,
	discountAbsoluteGross: CompareFields.discountAbsoluteGross,
	discountAbsoluteGrossOc: CompareFields.discountAbsoluteGrossOc,
	discountComment: CompareFields.discountComment,
	totalNoDiscount: CompareFields.totalNoDiscount,
	totalOcNoDiscount: CompareFields.totalOcNoDiscount,
	commentClient: CompareFields.commentClient,
	commentContractor: CompareFields.commentContractor,
	factoredQuantity: CompareFields.factoredQuantity,
	isFreeQuantity: CompareFields.isFreeQuantity,
	absoluteDifference: CompareFields.absoluteDifference,
	discountSplit: CompareFields.discountSplit,
	discountSplitOc: CompareFields.discountSplitOc,
	externalCode: CompareFields.externalCode,
	budgetPerUnit: CompareFields.budgetPerUnit,
	budgetTotal: CompareFields.budgetTotal,
	uomFk: CompareFields.uomFk,
	factorPriceUnit: CompareFields.factorPriceUnit,
	exQtnIsEvaluated: CompareFields.exQtnIsEvaluated,
	notSubmitted: CompareFields.notSubmitted,
	paymentTermPaFk: CompareFields.paymentTermPaFk,
	paymentTermFiFk: CompareFields.paymentTermFiFk,
	co2Project: CompareFields.co2Project,
	co2ProjectTotal: CompareFields.co2ProjectTotal,
	co2Source: CompareFields.co2Source,
	co2SourceTotal: CompareFields.co2SourceTotal,
	prjChangeFk: CompareFields.prjChangeFk,
	prjChangeStatusFk: CompareFields.prjChangeStatusFk,
	factoredTotalPrice: CompareFields.factoredTotalPrice
};